# Copyright (C) 2024 Richard Stiskalek
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
"""
MPI script for fitting density profiles to halo data.

Uses dynamic work distribution (master-worker pattern) where rank 0
distributes batches of functions to worker ranks.
"""
import warnings
from argparse import ArgumentParser
from pathlib import Path
from time import time

import numpy as np
import h5py
from mpi4py import MPI

import cdmprof
from utils import read_config

# MPI tags
WORK_TAG = 1
DONE_TAG = 0


def get_completed_func_idx(temp_dir):
    """
    Read all rank files and return set of completed func_idx.

    Parameters
    ----------
    temp_dir : Path
        Directory containing results_rank*.hdf5 files.

    Returns
    -------
    set of int
        Set of func_idx that have been completed.
    """
    temp_dir = Path(temp_dir)
    completed = set()

    for fpath in temp_dir.glob("results_rank*.hdf5"):
        try:
            with h5py.File(fpath, 'r') as f:
                if 'func_idx' in f:
                    completed.update(f['func_idx'][:].tolist())
        except Exception:
            # File might be corrupted or incomplete
            continue

    return completed


def load_skip_functions(skip_path):
    """
    Load skip file generated by generate_functions.py.

    File format: `idx reason equation`

    Parameters
    ----------
    skip_path : Path
        Path to skip_functions_{comp}.txt file.

    Returns
    -------
    dict
        Dictionary mapping func_idx -> reason for skipping.
    """
    skip_path = Path(skip_path)
    skip_dict = {}

    if not skip_path.exists():
        return skip_dict

    with open(skip_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            # Format: idx reason equation
            parts = line.split(maxsplit=2)
            if len(parts) >= 2:
                idx, reason = parts[0], parts[1]
                skip_dict[int(idx)] = reason

    return skip_dict


def clear_temp_dir(temp_dir):
    """
    Remove all files in temp directory and the directory itself.

    Parameters
    ----------
    temp_dir : Path
        Directory to clear.
    """
    temp_dir = Path(temp_dir)
    if not temp_dir.exists():
        return

    for fpath in temp_dir.glob("*"):
        fpath.unlink()

    temp_dir.rmdir()


def print_failed_functions(output_path, equations):
    """
    Print functions that failed to produce any results.

    Parameters
    ----------
    output_path : Path
        Path to merged HDF5 results file.
    equations : list of str
        List of equation strings.
    """
    output_path = Path(output_path)

    if not output_path.exists():
        print("No results file found.")
        return

    with h5py.File(output_path, 'r') as f:
        if 'func_idx' not in f:
            successful = set()
        else:
            successful = set(f['func_idx'][:].tolist())

        # Load negative loss rejections if available
        if 'negative_loss_func_idx' in f:
            negative_loss_funcs = set(f['negative_loss_func_idx'][:].tolist())
        else:
            negative_loss_funcs = set()

        # Load asymptote rejections if available
        if 'asymp_reject_func_idx' in f:
            asymp_reject_funcs = set(f['asymp_reject_func_idx'][:].tolist())
        else:
            asymp_reject_funcs = set()

    all_funcs = set(range(len(equations)))
    failed = all_funcs - successful

    if len(failed) == 0:
        print(f"\nAll {len(equations)} functions produced results.")
        return

    print(f"\n{'=' * 80}")
    print(f"SKIPPED/FAILED FUNCTIONS ({len(failed)}/{len(equations)})")
    print("=" * 80)

    # Categorize failures
    norm_only = []
    bad_funcs = []
    negative_loss = []
    asymp_rejects = []
    other_fails = []

    for fidx in sorted(failed):
        eq = equations[fidx]
        # Check negative loss first (from actual fitting)
        if fidx in negative_loss_funcs:
            negative_loss.append((fidx, eq))
        # Check asymptote rejections (from post-fit validation)
        elif fidx in asymp_reject_funcs:
            asymp_rejects.append((fidx, eq))
        # Check normalization-only (more specific)
        elif cdmprof.fitting._has_normalization_only_param(eq):
            norm_only.append((fidx, eq))
        elif cdmprof.fitting.is_bad_function(eq):
            bad_funcs.append((fidx, eq))
        else:
            other_fails.append((fidx, eq))

    # Print negative loss functions
    if len(negative_loss) > 0:
        print(f"\nNegative loss (numerical issues/singularities): "
              f"{len(negative_loss)}")
        if len(negative_loss) <= 20:
            for fidx, eq in negative_loss:
                eq_short = eq[:50] + "..." if len(eq) > 50 else eq
                print(f"  {fidx}: {eq_short}")
        else:
            for fidx, eq in negative_loss[:10]:
                eq_short = eq[:50] + "..." if len(eq) > 50 else eq
                print(f"  {fidx}: {eq_short}")
            print(f"  ... and {len(negative_loss) - 10} more")

    # Print asymptote rejection functions
    if len(asymp_rejects) > 0:
        print(f"\nAsymptote validation failed: {len(asymp_rejects)}")
        if len(asymp_rejects) <= 20:
            for fidx, eq in asymp_rejects:
                eq_short = eq[:50] + "..." if len(eq) > 50 else eq
                print(f"  {fidx}: {eq_short}")
        else:
            for fidx, eq in asymp_rejects[:10]:
                eq_short = eq[:50] + "..." if len(eq) > 50 else eq
                print(f"  {fidx}: {eq_short}")
            print(f"  ... and {len(asymp_rejects) - 10} more")

    # Print normalization-only functions
    if len(norm_only) > 0:
        print(f"\nNormalization-only parameter (skipped): {len(norm_only)}")
        if len(norm_only) <= 20:
            for fidx, eq in norm_only:
                eq_short = eq[:50] + "..." if len(eq) > 50 else eq
                print(f"  {fidx}: {eq_short}")
        else:
            for fidx, eq in norm_only[:10]:
                eq_short = eq[:50] + "..." if len(eq) > 50 else eq
                print(f"  {fidx}: {eq_short}")
            print(f"  ... and {len(norm_only) - 10} more")

    # Print bad functions (nan/inf/trig)
    if len(bad_funcs) > 0:
        print(f"\nBad functions (nan/inf/trig, skipped): {len(bad_funcs)}")
        if len(bad_funcs) <= 20:
            for fidx, eq in bad_funcs:
                eq_short = eq[:50] + "..." if len(eq) > 50 else eq
                print(f"  {fidx}: {eq_short}")
        else:
            for fidx, eq in bad_funcs[:10]:
                eq_short = eq[:50] + "..." if len(eq) > 50 else eq
                print(f"  {fidx}: {eq_short}")
            print(f"  ... and {len(bad_funcs) - 10} more")

    # Print other failures
    if len(other_fails) > 0:
        print(f"\nCompilation/fit failures: {len(other_fails)}")
        for fidx, eq in other_fails:
            eq_short = eq[:50] + "..." if len(eq) > 50 else eq
            print(f"  {fidx}: {eq_short}")

    print("=" * 80)
    print("")


def print_asymptote_summary(n_param_dep, n_unknown, n_rejected, threshold_inf,
                            threshold_zero):
    """
    Print summary of post-fit asymptote validation.

    Parameters
    ----------
    n_param_dep : int
        Number of functions with parameter-dependent asymptotes.
    n_unknown : int
        Number of functions with unknown asymptotes.
    n_rejected : int
        Number of functions rejected by asymptote validation.
    threshold_inf : float
        Threshold for x->inf validation.
    threshold_zero : float
        Threshold for x->0+ validation.
    """
    n_total = n_param_dep + n_unknown
    if n_total == 0:
        return

    n_passed = n_total - n_rejected
    pct_passed = 100 * n_passed / n_total if n_total > 0 else 0
    pct_rejected = 100 * n_rejected / n_total if n_total > 0 else 0

    print(f"\n{'=' * 60}")
    print("POST-FIT ASYMPTOTE VALIDATION")
    print("=" * 60)
    print(f"Thresholds: lim(x->inf)~0 >= {100*threshold_inf:.0f}%, "
          f"lim(x->0+)>0 >= {100*threshold_zero:.0f}%")
    print("\nFunctions requiring post-fit check:")
    print(f"  Parameter-dependent:  {n_param_dep:>5}")
    print(f"  Unknown (recomputed): {n_unknown:>5}")
    print(f"  Total:                {n_total:>5}")
    print("\nResults:")
    print(f"  Passed:   {n_passed:>5} ({pct_passed:.1f}%)")
    print(f"  Rejected: {n_rejected:>5} ({pct_rejected:.1f}%)")
    print("=" * 60)


def compute_nfw_scores(binned, fit_config, return_per_halo=False):
    """
    Compute the NFW reference score for comparison.

    NFW profile: rho(x) = 1 / (x * (1 + x)^2)

    Parameters
    ----------
    binned : dict
        Binned halo data from HaloCollection.bin().
    fit_config : dict
        Fitting configuration parameters.
    return_per_halo : bool, optional
        If True, also return per-halo normalized losses.

    Returns
    -------
    float or None
        NFW score (sum of loss/npart), or None if fitting fails.
    np.ndarray or None (only if return_per_halo=True)
        Per-halo loss/npart values (nan for failed fits).
    """
    nfw_expr = "1 / (x * (1 + x)**2)"

    try:
        fitter = cdmprof.compile_fitter(nfw_expr)
    except Exception as e:
        print(f"Failed to compile NFW profile: {e}", flush=True)
        if return_per_halo:
            return None, None
        return None

    nhalo = len(binned['halo_ids'])
    total_score = 0.0
    n_success = 0
    per_halo_scores = np.full(nhalo, np.nan)

    for halo_idx in range(nhalo):
        try:
            result = fitter.fit_with_restarts(
                binned['bin_counts'][halo_idx],
                binned['bin_positions'][halo_idx],
                binned['rmin'][halo_idx],
                binned['rmax'][halo_idx],
                max_restarts=fit_config['max_restarts'],
                nconv_required=fit_config['nconv_required'],
                conv_rtol=fit_config['conv_rtol'],
                Rs_lower_factor=fit_config.get('Rs_lower_factor'),
                Rs_upper_factor=fit_config.get('Rs_upper_factor'),
                a_lower=fit_config.get('a_lower'),
                a_upper=fit_config.get('a_upper'),
                xtol=fit_config['xtol'],
                ftol=fit_config['ftol'],
                maxeval=fit_config['maxeval'],
                seed=42 + halo_idx,
            )

            if result['params'] is not None:
                npart = np.sum(binned['bin_counts'][halo_idx])
                norm_loss = result['loss'] / npart
                total_score += norm_loss
                per_halo_scores[halo_idx] = norm_loss
                n_success += 1
        except Exception:
            pass

    if n_success == 0:
        if return_per_halo:
            return None, None
        return None

    # Penalize for missing halos
    if n_success < nhalo:
        median_score = total_score / n_success
        total_score += (nhalo - n_success) * median_score

    # Convert to per-halo average
    avg_score = total_score / nhalo

    if return_per_halo:
        return avg_score, per_halo_scores
    return avg_score


def check_postfit_asymptotes(func_idx, expr_str, func_results, binned,
                             fit_config, asymp_inf_threshold,
                             asymp_zero_threshold, print_prefix=""):
    """
    Check post-fit asymptotes for a function.

    Parameters
    ----------
    func_idx : int
        Function index.
    expr_str : str
        Expression string.
    func_results : list
        List of (func_idx, halo_id, loss, params, converged, neval) tuples.
    binned : dict
        Binned halo data.
    fit_config : dict
        Fitting configuration.
    asymp_inf_threshold : float
        Threshold for x->inf asymptote pass rate.
    asymp_zero_threshold : float
        Threshold for x->0+ asymptote pass rate.
    print_prefix : str, optional
        Prefix for verbose output (e.g., "Rank 0: ").

    Returns
    -------
    tuple
        (reject, n_pass_inf, n_pass_zero, n_checked)
    """
    n_total = len(func_results)
    round_dec = fit_config.get('asymp_round_decimals', 5)
    asymp_timeout = fit_config.get('asymp_timeout', 0)
    asymp_verbose = fit_config.get('asymp_verbose', False)
    asymp_n_halos = fit_config.get('asymp_n_halos', 10)

    # Sample halos if asymp_n_halos is set and less than total
    if asymp_n_halos > 0 and asymp_n_halos < n_total:
        rng = np.random.default_rng(seed=42)
        sample_idx = rng.choice(n_total, size=asymp_n_halos, replace=False)
        results_to_check = [func_results[i] for i in sorted(sample_idx)]
    else:
        results_to_check = func_results

    n_checked = len(results_to_check)
    n_pass_inf = 0
    n_pass_zero = 0

    if asymp_verbose:
        # Compute avg normalized loss (loss/npart) over all results
        norm_losses = []
        for r in func_results:
            halo_id = r[1]
            npart = np.sum(binned['bin_counts'][halo_id])
            norm_losses.append(r[2] / npart)
        avg_norm_loss = np.mean(norm_losses)
        print(f"{print_prefix}func {func_idx} asymptote check "
              f"(avg_loss/npart={avg_norm_loss:.4f}, "
              f"n_check={n_checked}/{n_total}): {expr_str}", flush=True)

    for i_r, r in enumerate(results_to_check):
        params = r[3]
        halo_id = r[1]
        if asymp_verbose:
            print(f"  {print_prefix}halo {i_r+1}/{n_checked} "
                  f"(id={halo_id}) fit done", flush=True)
            print(f"    params={params}", flush=True)
        lim_zero, lim_inf = cdmprof.compute_asymptotes_with_params(
            expr_str, params, round_decimals=round_dec, timeout=asymp_timeout)
        if asymp_verbose:
            print(f"    limit done: x->0+={lim_zero}, x->inf={lim_inf}",
                  flush=True)

        if cdmprof.fitting.check_asymptote_inf(lim_inf):
            n_pass_inf += 1
        if cdmprof.fitting.check_asymptote_zero(lim_zero):
            n_pass_zero += 1

    # Check thresholds
    reject = False
    frac_pass_inf = n_pass_inf / n_checked
    if frac_pass_inf < asymp_inf_threshold:
        reject = True
    frac_pass_zero = n_pass_zero / n_checked
    if frac_pass_zero < asymp_zero_threshold:
        reject = True

    return reject, n_pass_inf, n_pass_zero, n_checked


def print_best_results(output_path, equations, npart_per_halo,
                       asymp_postfit_funcs=None, nfw_score=None, n_top=100):
    """
    Print a table of the best functions ranked by normalized loss.

    Score = sum over halos of (loss / npart), lower is better.
    Functions that fail on some halos are penalized by adding
    n_missing * median(loss/npart) to their score.

    Parameters
    ----------
    output_path : Path
        Path to merged HDF5 results file.
    equations : list of str
        List of equation strings.
    npart_per_halo : array-like
        Number of particles per halo.
    asymp_postfit_funcs : set, optional
        Set of func_idx that had post-fit asymptote validation.
    nfw_score : float, optional
        NFW reference score for comparison.
    n_top : int, optional
        Number of top functions to display.
    """
    output_path = Path(output_path)
    if not output_path.exists():
        print("No results file found for ranking.")
        return

    if asymp_postfit_funcs is None:
        asymp_postfit_funcs = set()

    with h5py.File(output_path, 'r') as f:
        func_idx = f['func_idx'][:]
        halo_idx = f['halo_idx'][:]
        loss = f['loss'][:]

        # Load asymptote pass fractions if available
        asymp_pass_dict = {}  # func_idx -> (n_pass_inf, n_pass_zero, n_total)
        if 'asymp_pass_func_idx' in f:
            apf_idx = f['asymp_pass_func_idx'][:]
            apf_inf = f['asymp_pass_inf'][:]
            apf_zero = f['asymp_pass_zero'][:]
            apf_total = f['asymp_pass_total'][:]
            for i, fidx in enumerate(apf_idx):
                asymp_pass_dict[int(fidx)] = (
                    int(apf_inf[i]), int(apf_zero[i]), int(apf_total[i]))

    # Compute normalized loss per result
    npart_per_halo = np.asarray(npart_per_halo)
    n_halos_total = len(npart_per_halo)
    normalized_loss = loss / npart_per_halo[halo_idx]

    # Compute score per function: average of normalized losses across halos
    # Penalize functions that fail on some halos
    unique_funcs = np.unique(func_idx)
    scores = []

    for fidx in unique_funcs:
        mask = func_idx == fidx
        norm_losses = normalized_loss[mask]
        n_halos_fitted = len(norm_losses)
        n_missing = n_halos_total - n_halos_fitted

        # Base score: sum of normalized losses
        total_score = np.sum(norm_losses)

        # Penalty for missing halos: add n_missing * median
        if n_missing > 0 and n_halos_fitted > 0:
            median_loss = np.median(norm_losses)
            total_score += n_missing * median_loss

        # Convert to per-halo average
        avg_score = total_score / n_halos_total

        scores.append((fidx, avg_score, n_halos_fitted))

    # Sort by score (lower is better)
    scores.sort(key=lambda x: x[1])

    # Print NFW reference score
    if nfw_score is not None:
        print("\n" + "-" * 79)
        print(f"NFW REFERENCE: AvgScore = {nfw_score:.4f}  "
              f"(rho = 1 / (x * (1 + x)^2))")
        print("-" * 79)

    # Print table
    print("\n" + "=" * 79)
    print("TOP FUNCTIONS (ranked by avg loss/npart per halo, lower is better)")
    print("=" * 79)
    header = f"{'Rank':<6} {'Func#':<8} {'AvgScore':<12} {'#Halos':<8} "
    header += f"{'Asymp':<8} Equation"
    print(header)
    print("-" * 79)

    for rank, (fidx, score, n_halos) in enumerate(scores[:n_top], 1):
        eq = equations[fidx]
        # Truncate equation if too long
        if len(eq) > 35:
            eq = eq[:32] + "..."
        # Asymptote check status: show pass fraction if available
        if fidx in asymp_pass_dict:
            n_inf, n_zero, n_total = asymp_pass_dict[fidx]
            if n_total > 0:
                frac_inf = n_inf / n_total
                frac_zero = n_zero / n_total
                asymp_status = f"{100*frac_inf:.0f}/{100*frac_zero:.0f}"
            else:
                asymp_status = "-"
        elif fidx in asymp_postfit_funcs:
            asymp_status = "?"
        else:
            asymp_status = "-"
        row = f"{rank:<6} {fidx:<8} {score:<12.4f} {n_halos:<8} "
        row += f"{asymp_status:<8} {eq}"
        print(row)

    print("=" * 79)
    print(f"Showing top {min(n_top, len(scores))} of {len(scores)} functions")
    print("(Scores penalized for missing halos: n_missing * median)")
    print("(Asymp: inf%/zero% pass fractions for x->inf and x->0+ checks)")
    print("")


def merge_results(input_dir, output_path, delete_rank_files=True):
    """
    Merge all results_rank*.hdf5 files into a single output file.

    Parameters
    ----------
    input_dir : Path
        Directory containing results_rank*.hdf5 files.
    output_path : Path
        Output file path.
    delete_rank_files : bool, optional
        If True, delete input files after merging.

    Returns
    -------
    int
        Total number of results merged.
    """
    input_dir = Path(input_dir)
    output_path = Path(output_path)

    rank_files = sorted(input_dir.glob("results_rank*.hdf5"))

    if len(rank_files) == 0:
        print(f"No results_rank*.hdf5 files found in {input_dir}")
        return 0

    print(f"Merging {len(rank_files)} rank files...", flush=True)

    all_func_idx = []
    all_halo_idx = []
    all_loss = []
    all_params = []
    all_converged = []
    all_neval = []
    all_negative_loss_func_idx = set()
    all_asymp_reject_func_idx = set()
    all_asymp_pass_fractions = {}  # func_idx -> (n_inf, n_zero, n_total)
    equations = None

    for fpath in rank_files:
        with h5py.File(fpath, 'r') as f:
            if 'func_idx' in f:
                all_func_idx.append(f['func_idx'][:])
                all_halo_idx.append(f['halo_idx'][:])
                all_loss.append(f['loss'][:])
                all_params.append(f['params'][:])
                all_converged.append(f['converged'][:])
                all_neval.append(f['neval'][:])

            if equations is None and 'equations' in f:
                equations = f['equations'][:]

            # Collect negative loss func indices
            if 'negative_loss_func_idx' in f:
                all_negative_loss_func_idx.update(
                    f['negative_loss_func_idx'][:].tolist())

            # Collect asymptote rejection func indices
            if 'asymp_reject_func_idx' in f:
                all_asymp_reject_func_idx.update(
                    f['asymp_reject_func_idx'][:].tolist())

            # Collect asymptote pass fractions
            if 'asymp_pass_func_idx' in f:
                apf_idx = f['asymp_pass_func_idx'][:]
                apf_inf = f['asymp_pass_inf'][:]
                apf_zero = f['asymp_pass_zero'][:]
                apf_total = f['asymp_pass_total'][:]
                for i, fidx in enumerate(apf_idx):
                    all_asymp_pass_fractions[int(fidx)] = (
                        int(apf_inf[i]), int(apf_zero[i]), int(apf_total[i]))

    if len(all_func_idx) == 0:
        print("No data to merge")
        return 0

    func_idx = np.concatenate(all_func_idx)
    halo_idx = np.concatenate(all_halo_idx)
    loss = np.concatenate(all_loss)
    converged = np.concatenate(all_converged)
    neval = np.concatenate(all_neval)

    # Pad params arrays to same size before concatenating
    max_nparams = max(p.shape[1] for p in all_params)
    padded_params = []
    for p in all_params:
        if p.shape[1] < max_nparams:
            pad_width = ((0, 0), (0, max_nparams - p.shape[1]))
            p = np.pad(p, pad_width, constant_values=np.nan)
        padded_params.append(p)
    params = np.concatenate(padded_params)

    n_total = len(func_idx)
    n_funcs = len(np.unique(func_idx))
    n_halos = len(np.unique(halo_idx))

    with h5py.File(output_path, 'w') as f:
        f.create_dataset('func_idx', data=func_idx)
        f.create_dataset('halo_idx', data=halo_idx)
        f.create_dataset('loss', data=loss)
        f.create_dataset('params', data=params)
        f.create_dataset('converged', data=converged)
        f.create_dataset('neval', data=neval)

        if equations is not None:
            dt = h5py.special_dtype(vlen=str)
            f.create_dataset('equations', data=equations, dtype=dt)

        # Store negative loss function indices
        if len(all_negative_loss_func_idx) > 0:
            neg_idx = np.array(sorted(all_negative_loss_func_idx),
                               dtype=np.int32)
            f.create_dataset('negative_loss_func_idx', data=neg_idx)

        # Store asymptote rejection function indices
        if len(all_asymp_reject_func_idx) > 0:
            asymp_idx = np.array(sorted(all_asymp_reject_func_idx),
                                 dtype=np.int32)
            f.create_dataset('asymp_reject_func_idx', data=asymp_idx)

        # Store asymptote pass fractions
        if len(all_asymp_pass_fractions) > 0:
            n_apf = len(all_asymp_pass_fractions)
            apf_func_idx = np.zeros(n_apf, dtype=np.int32)
            apf_pass_inf = np.zeros(n_apf, dtype=np.int32)
            apf_pass_zero = np.zeros(n_apf, dtype=np.int32)
            apf_total = np.zeros(n_apf, dtype=np.int32)
            for i, (fidx, (n_inf, n_zero, n_tot)) in enumerate(
                    sorted(all_asymp_pass_fractions.items())):
                apf_func_idx[i] = fidx
                apf_pass_inf[i] = n_inf
                apf_pass_zero[i] = n_zero
                apf_total[i] = n_tot
            f.create_dataset('asymp_pass_func_idx', data=apf_func_idx)
            f.create_dataset('asymp_pass_inf', data=apf_pass_inf)
            f.create_dataset('asymp_pass_zero', data=apf_pass_zero)
            f.create_dataset('asymp_pass_total', data=apf_total)

        f.attrs['n_results'] = n_total
        f.attrs['n_functions'] = n_funcs
        f.attrs['n_halos'] = n_halos

    print(f"Merged {n_total} results ({n_funcs} functions, {n_halos} halos)",
          flush=True)
    if len(all_negative_loss_func_idx) > 0:
        print(f"  {len(all_negative_loss_func_idx)} functions rejected "
              f"(negative loss)", flush=True)
    if len(all_asymp_reject_func_idx) > 0:
        print(f"  {len(all_asymp_reject_func_idx)} functions rejected "
              f"(asymptote validation)", flush=True)
    print(f"Wrote merged results to {output_path}", flush=True)

    if delete_rank_files:
        for fpath in rank_files:
            fpath.unlink()

    return n_total


def write_results(fpath, results, equations, negative_loss_func_idx=None,
                  asymp_reject_func_idx=None, asymp_pass_fractions=None):
    """
    Write fit results to HDF5 file.

    Parameters
    ----------
    fpath : str or Path
        Output file path.
    results : list of tuples
        Each tuple: (func_idx, halo_idx, loss, params, converged, neval)
    equations : list of str
        Equation strings for reference.
    negative_loss_func_idx : set or list, optional
        Function indices that were rejected due to negative loss.
    asymp_reject_func_idx : set or list, optional
        Function indices that were rejected due to asymptote validation.
    asymp_pass_fractions : dict, optional
        func_idx -> (n_pass_inf, n_pass_zero, n_total) for post-fit
        asymptote checks.
    """
    no_data = (len(results) == 0 and not negative_loss_func_idx
               and not asymp_reject_func_idx)
    if no_data:
        return

    with h5py.File(fpath, 'w') as f:
        if len(results) > 0:
            func_idx = np.array([r[0] for r in results], dtype=np.int32)
            halo_idx = np.array([r[1] for r in results], dtype=np.int32)
            loss = np.array([r[2] for r in results], dtype=np.float64)
            converged = np.array([r[4] for r in results], dtype=np.int32)
            neval = np.array([r[5] for r in results], dtype=np.int32)

            # Pad params to fixed size (max nparams across all results)
            max_nparams = max(len(r[3]) for r in results)
            params = np.full((len(results), max_nparams), np.nan,
                             dtype=np.float64)
            for i, r in enumerate(results):
                params[i, :len(r[3])] = r[3]

            f.create_dataset('func_idx', data=func_idx)
            f.create_dataset('halo_idx', data=halo_idx)
            f.create_dataset('loss', data=loss)
            f.create_dataset('params', data=params)
            f.create_dataset('converged', data=converged)
            f.create_dataset('neval', data=neval)

        # Store equations as variable-length strings
        dt = h5py.special_dtype(vlen=str)
        eq_data = np.array(equations, dtype=object)
        f.create_dataset('equations', data=eq_data, dtype=dt)

        # Store negative loss function indices
        if negative_loss_func_idx:
            neg_idx = np.array(sorted(negative_loss_func_idx), dtype=np.int32)
            f.create_dataset('negative_loss_func_idx', data=neg_idx)

        # Store asymptote rejection function indices
        if asymp_reject_func_idx:
            asymp_idx = np.array(sorted(asymp_reject_func_idx), dtype=np.int32)
            f.create_dataset('asymp_reject_func_idx', data=asymp_idx)

        # Store asymptote pass fractions
        if asymp_pass_fractions:
            n_funcs = len(asymp_pass_fractions)
            apf_func_idx = np.zeros(n_funcs, dtype=np.int32)
            apf_pass_inf = np.zeros(n_funcs, dtype=np.int32)
            apf_pass_zero = np.zeros(n_funcs, dtype=np.int32)
            apf_total = np.zeros(n_funcs, dtype=np.int32)
            for i, (fidx, (n_inf, n_zero, n_tot)) in enumerate(
                    sorted(asymp_pass_fractions.items())):
                apf_func_idx[i] = fidx
                apf_pass_inf[i] = n_inf
                apf_pass_zero[i] = n_zero
                apf_total[i] = n_tot
            f.create_dataset('asymp_pass_func_idx', data=apf_func_idx)
            f.create_dataset('asymp_pass_inf', data=apf_pass_inf)
            f.create_dataset('asymp_pass_zero', data=apf_pass_zero)
            f.create_dataset('asymp_pass_total', data=apf_total)


def master_loop(comm, job_queue, batch_size):
    """
    Master process: distribute work to workers.

    Parameters
    ----------
    comm : MPI.Comm
        MPI communicator.
    job_queue : list of int
        List of func_idx to process.
    batch_size : int
        Number of functions per batch.
    """
    size = comm.Get_size()
    n_workers = size - 1

    job_queue = list(job_queue)  # Make a copy
    n_total = len(job_queue)
    workers_done = 0

    print(f"Master: {n_total} functions to process, {n_workers} workers, "
          f"batch size {batch_size}", flush=True)

    while workers_done < n_workers:
        # Wait for any worker to request work
        status = MPI.Status()
        worker_rank = comm.recv(source=MPI.ANY_SOURCE, tag=MPI.ANY_TAG,
                                status=status)

        if len(job_queue) > 0:
            # Send next batch
            batch = job_queue[:batch_size]
            job_queue = job_queue[batch_size:]
            comm.send(batch, dest=worker_rank, tag=WORK_TAG)
            print(f"Master: sent {len(batch)} jobs to rank {worker_rank}, "
                  f"{len(job_queue)} remaining", flush=True)
        else:
            # No more work, tell worker to finish
            comm.send(None, dest=worker_rank, tag=DONE_TAG)
            workers_done += 1
            print(f"Master: rank {worker_rank} done, "
                  f"{n_workers - workers_done} workers remaining", flush=True)


def worker_loop(comm, equations, binned, output_dir, fit_config,
                asymp_inf_param_dep, asymp_zero_param_dep, asymp_unknown,
                nfw_per_halo=None):
    """
    Worker process: request work, fit functions, save results.

    Parameters
    ----------
    comm : MPI.Comm
        MPI communicator.
    equations : list of str
        List of equations.
    binned : dict
        Binned halo data from HaloCollection.bin().
    output_dir : Path
        Output directory.
    fit_config : dict
        Fitting configuration parameters.
    asymp_inf_param_dep : dict
        func_idx -> limit_expr for x->inf param-dependent asymptotes.
    asymp_zero_param_dep : dict
        func_idx -> limit_expr for x->0+ param-dependent asymptotes.
    asymp_unknown : set
        func_idx for functions needing post-fit asymptote computation.
    nfw_per_halo : np.ndarray, optional
        Per-halo NFW normalized losses for early stopping comparison.
    """
    rank = comm.Get_rank()
    results = []
    negative_loss_func_idx = set()
    asymp_reject_func_idx = set()
    # Track pass fractions: func_idx -> (n_pass_inf, n_pass_zero, n_total)
    asymp_pass_fractions = {}

    nhalo = len(binned['halo_ids'])
    asymp_inf_threshold = fit_config.get('asymp_inf_threshold', 0.5)
    asymp_zero_threshold = fit_config.get('asymp_zero_threshold', 0.5)

    # NFW comparison settings
    nfw_early_stop_halos = fit_config.get('nfw_early_stop_halos', 5)
    nfw_early_stop_factor = fit_config.get('nfw_early_stop_factor', 2.0)
    use_nfw_early_stop = (fit_config.get('nfw_early_stop_enabled', False)
                          and nfw_per_halo is not None
                          and np.any(~np.isnan(nfw_per_halo)))
    if use_nfw_early_stop:
        nfw_avg = np.nanmean(nfw_per_halo)
    else:
        nfw_avg = None

    while True:
        # Request work from master
        comm.send(rank, dest=0)

        # Receive response
        status = MPI.Status()
        batch = comm.recv(source=0, tag=MPI.ANY_TAG, status=status)

        if status.tag == DONE_TAG:
            break

        # Process batch of functions
        t_batch_start = time()
        n_funcs_batch = len(batch)

        for func_idx in batch:
            expr_str = equations[func_idx]

            # Skip bad functions silently
            if cdmprof.fitting.is_bad_function(expr_str):
                continue

            try:
                fitter = cdmprof.compile_fitter(expr_str)
            except Exception as e:
                print(f"Rank {rank}: failed to compile func {func_idx} "
                      f"'{expr_str}': {e}", flush=True)
                continue

            # Fit to all halos, collecting results temporarily
            func_results = []
            func_norm_losses = []  # Track normalized losses for NFW comparison
            n_negative_loss = 0
            n_consecutive_failures = 0
            early_stop_threshold = fit_config.get('early_stop_failures', 5)
            early_stopped = False
            nfw_early_stopped = False

            for halo_idx in range(nhalo):
                try:
                    result = fitter.fit_with_restarts(
                        binned['bin_counts'][halo_idx],
                        binned['bin_positions'][halo_idx],
                        binned['rmin'][halo_idx],
                        binned['rmax'][halo_idx],
                        max_restarts=fit_config['max_restarts'],
                        nconv_required=fit_config['nconv_required'],
                        conv_rtol=fit_config['conv_rtol'],
                        Rs_lower_factor=fit_config.get('Rs_lower_factor'),
                        Rs_upper_factor=fit_config.get('Rs_upper_factor'),
                        a_lower=fit_config.get('a_lower'),
                        a_upper=fit_config.get('a_upper'),
                        xtol=fit_config['xtol'],
                        ftol=fit_config['ftol'],
                        maxeval=fit_config['maxeval'],
                        seed=42 + halo_idx,
                    )

                    # Skip if fit failed (params is None)
                    if result['params'] is None:
                        if result.get('reject_reason') == 'negative_loss':
                            n_negative_loss += 1
                        # Track consecutive failures for early stopping
                        if len(func_results) == 0:
                            n_consecutive_failures += 1
                            if n_consecutive_failures >= early_stop_threshold:
                                early_stopped = True
                                break
                        continue

                    # Reset consecutive failures on success
                    n_consecutive_failures = 0

                    # Compute normalized loss for this halo
                    npart = np.sum(binned['bin_counts'][halo_idx])
                    norm_loss = result['loss'] / npart
                    func_norm_losses.append(norm_loss)

                    func_results.append((
                        func_idx,
                        halo_idx,
                        result['loss'],
                        result['params'],
                        result['converged'],
                        result['neval'],
                    ))

                    # NFW comparison early stopping
                    if (use_nfw_early_stop and
                            len(func_results) >= nfw_early_stop_halos):
                        func_avg = np.mean(func_norm_losses)
                        if func_avg > nfw_avg + nfw_early_stop_factor:
                            nfw_early_stopped = True
                            break

                except Exception as e:
                    print(f"Rank {rank}: func {func_idx}, halo {halo_idx} "
                          f"failed: {e}", flush=True)
                    # Track consecutive failures for early stopping
                    if len(func_results) == 0:
                        n_consecutive_failures += 1
                        if n_consecutive_failures >= early_stop_threshold:
                            early_stopped = True
                            break

            if early_stopped:
                print(f"Rank {rank}: func {func_idx} early stopped after "
                      f"{early_stop_threshold} failures", flush=True)
                continue

            if nfw_early_stopped:
                # Skip function entirely (don't save partial results)
                func_avg = np.mean(func_norm_losses)
                threshold = nfw_avg + nfw_early_stop_factor
                print(f"Rank {rank}: NFW early stopped '{expr_str}' "
                      f"(avg={func_avg:.4f} > {threshold:.4f})", flush=True)
                continue

            # Check if function should be rejected
            n_success = len(func_results)

            if n_success == 0:
                if n_negative_loss > 0:
                    negative_loss_func_idx.add(func_idx)
                    print(f"Rank {rank}: func {func_idx} rejected "
                          f"(negative loss) '{expr_str}'", flush=True)
                else:
                    print(f"Rank {rank}: all fits failed for func {func_idx} "
                          f"'{expr_str}'", flush=True)
                continue

            # Post-fit asymptote validation for parameter-dependent asymptotes
            reject_asymp = False
            skip_asymp = fit_config.get('skip_postfit_asymp_check', False)
            has_inf_check = func_idx in asymp_inf_param_dep
            has_zero_check = func_idx in asymp_zero_param_dep
            has_unknown_check = func_idx in asymp_unknown
            needs_postfit_check = (has_inf_check or has_zero_check
                                   or has_unknown_check)

            if needs_postfit_check and not skip_asymp:
                reject_asymp, n_pass_inf, n_pass_zero, n_checked = \
                    check_postfit_asymptotes(
                        func_idx, expr_str, func_results, binned, fit_config,
                        asymp_inf_threshold, asymp_zero_threshold,
                        print_prefix=f"Rank {rank}: ")
                asymp_pass_fractions[func_idx] = (
                    n_pass_inf, n_pass_zero, n_checked)

            if reject_asymp:
                asymp_reject_func_idx.add(func_idx)
                # Only skip results if rejection is enabled
                if fit_config.get('reject_asymp_failures', True):
                    continue

            results.extend(func_results)

        batch_time = time() - t_batch_start
        avg_per_func = batch_time / n_funcs_batch if n_funcs_batch > 0 else 0
        print(f"Rank {rank}: {n_funcs_batch} funcs in {batch_time:.1f}s | "
              f"{avg_per_func:.1f}s/func | {len(results)} total results",
              flush=True)

        # Write results after each batch for resume support
        if len(results) > 0 or len(negative_loss_func_idx) > 0:
            output_path = output_dir / f"results_rank{rank}.hdf5"
            write_results(output_path, results, equations,
                          negative_loss_func_idx, asymp_reject_func_idx,
                          asymp_pass_fractions)

    print(f"Rank {rank}: finished with {len(results)} total results",
          flush=True)


if __name__ == "__main__":
    # Load config first for defaults
    config = read_config()
    fit_config = config['fitting']

    parser = ArgumentParser(description="Fit density profiles with MPI")
    parser.add_argument("--complexity", type=int, required=True,
                        help="Equation complexity level")
    parser.add_argument("--halos", type=str, required=True,
                        help="Path to folder containing halo data")
    parser.add_argument("--resume", action="store_true",
                        help="Resume from existing results in temp directory")
    args = parser.parse_args()

    # Construct equations path from config
    runname = fit_config['runname']
    results_base = Path(config['path']['results'])
    equations_dir = results_base / runname / f"compl_{args.complexity}"
    equations_path = equations_dir / f"unique_equations_{args.complexity}.txt"
    skip_path = equations_dir / f"skip_functions_{args.complexity}.txt"
    asymp_inf_path = equations_dir / f"asymptotes_inf_{args.complexity}.txt"
    asymp_zero_path = equations_dir / f"asymptotes_zero_{args.complexity}.txt"

    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    size = comm.Get_size()

    # Derive output filename from halos folder, runname, and complexity
    halos_name = Path(args.halos).name
    output_fname = f"fit_{runname}_compl{args.complexity}_{halos_name}.hdf5"
    output_path = results_base / output_fname

    # Temp directory for rank files (not hidden)
    temp_dir_name = f"tmp_fit_{runname}_compl{args.complexity}_{halos_name}"
    temp_dir = results_base / temp_dir_name

    # Load equations (all ranks)
    equations = cdmprof.fitting.load_equations(equations_path)

    # Load skip file and asymptotes (pre-computed invalid functions)
    skip_func_idx = set()
    asymp_inf_param_dep = {}
    asymp_zero_param_dep = {}
    asymp_unknown = set()
    if rank == 0:
        # Load validation skip file
        skip_dict = load_skip_functions(skip_path)
        skip_func_idx = set(skip_dict.keys())

        # Load asymptotes and add pre-fit skips
        (asymp_skip, asymp_inf_param_dep,
         asymp_zero_param_dep, asymp_unknown) = \
            cdmprof.fitting.process_asymptotes(asymp_inf_path, asymp_zero_path)

        # Merge asymptote skips into skip_dict
        for idx, reason in asymp_skip.items():
            if idx not in skip_dict:
                skip_dict[idx] = reason
                skip_func_idx.add(idx)

        if len(skip_func_idx) > 0:
            print(f"Skipping {len(skip_func_idx)} pre-flagged functions:",
                  flush=True)
            # Count by reason
            reasons = {}
            for reason in skip_dict.values():
                reasons[reason] = reasons.get(reason, 0) + 1
            for reason, count in sorted(reasons.items()):
                print(f"  {reason}: {count}", flush=True)

        # Print param-dep and unknown asymptote counts
        n_inf_param = len(asymp_inf_param_dep)
        n_zero_param = len(asymp_zero_param_dep)
        n_unknown = len(asymp_unknown)
        if n_inf_param > 0 or n_zero_param > 0:
            print("Functions with parameter-dependent asymptotes:", flush=True)
            print(f"  x->inf: {n_inf_param}", flush=True)
            print(f"  x->0+:  {n_zero_param}", flush=True)
        if n_unknown > 0:
            print(f"Functions with unknown asymptotes (post-fit check): "
                  f"{n_unknown}", flush=True)

    # Broadcast to all ranks
    skip_func_idx = comm.bcast(skip_func_idx, root=0)
    asymp_inf_param_dep = comm.bcast(asymp_inf_param_dep, root=0)
    asymp_zero_param_dep = comm.bcast(asymp_zero_param_dep, root=0)
    asymp_unknown = comm.bcast(asymp_unknown, root=0)

    # Handle resume vs fresh start
    completed_func_idx = set()
    if rank == 0:
        if args.resume:
            if temp_dir.exists():
                completed_func_idx = get_completed_func_idx(temp_dir)
                if len(completed_func_idx) > 0:
                    n_done = len(completed_func_idx)
                    print(f"Resuming: found {n_done} completed functions",
                          flush=True)
            temp_dir.mkdir(parents=True, exist_ok=True)
        else:
            # Fresh start: clear any existing temp files
            if temp_dir.exists():
                print("Clearing existing temp directory", flush=True)
                clear_temp_dir(temp_dir)
            temp_dir.mkdir(parents=True, exist_ok=True)

    # Broadcast completed_func_idx to all ranks
    completed_func_idx = comm.bcast(completed_func_idx, root=0)
    comm.Barrier()

    # Build job queue (filter out completed and skipped functions)
    all_idx = range(len(equations))
    job_queue = [i for i in all_idx
                 if i not in completed_func_idx and i not in skip_func_idx]

    # DEBUG: Only test function 34
    # job_queue = [275]

    # Load and bin halos on rank 0, then broadcast to all
    if rank == 0:
        halos = cdmprof.load_from_folder(args.halos)
        binned = halos.bin(nbin=fit_config['nbin'])
        n_halos = halos.n_halos
        del halos

        print(f"Run: {runname}, complexity: {args.complexity}", flush=True)
        n_skipped = len(skip_func_idx)
        n_completed = len(completed_func_idx)
        print(f"Functions: {len(job_queue)} to fit "
              f"({n_skipped} skipped, {n_completed} completed, "
              f"{len(equations)} total)", flush=True)
        print(f"Halos: {n_halos}", flush=True)
        print(f"Total fits: {len(job_queue) * n_halos}", flush=True)
        print(f"Output: {output_path}", flush=True)
        print(f"Temp dir: {temp_dir}", flush=True)
        print("", flush=True)
    else:
        binned = None
        n_halos = None

    # Broadcast binned data to all ranks
    binned = comm.bcast(binned, root=0)
    n_halos = comm.bcast(n_halos, root=0)

    if size == 1:
        # Single process mode: do everything on one CPU
        print("Running in single-process mode", flush=True)
        asymp_n_halos = fit_config.get('asymp_n_halos', 10)
        if asymp_n_halos > 0:
            print(f"Asymptote checks: {asymp_n_halos} random halos", flush=True)
        else:
            print("Asymptote checks: all halos", flush=True)

        # Compute NFW per-halo scores upfront for early stopping comparison
        nfw_early_stop_halos = fit_config.get('nfw_early_stop_halos', 5)
        nfw_early_stop_factor = fit_config.get('nfw_early_stop_factor', 2.0)
        use_nfw_early_stop = fit_config.get('nfw_early_stop_enabled', False)

        nfw_score = None
        nfw_per_halo = None
        nfw_avg = None

        if use_nfw_early_stop:
            print("Computing NFW reference scores for early stopping...",
                  flush=True)
            with warnings.catch_warnings():
                warnings.filterwarnings("ignore", message="reimporting")
                nfw_score, nfw_per_halo = compute_nfw_scores(
                    binned, fit_config, return_per_halo=True)
            nfw_valid = (nfw_per_halo is not None
                         and np.any(~np.isnan(nfw_per_halo)))
            if nfw_valid:
                nfw_avg = np.nanmean(nfw_per_halo)
                print(f"NFW avg score: {nfw_avg:.4f}", flush=True)
                threshold = nfw_avg + nfw_early_stop_factor
                print(f"NFW early stop: after {nfw_early_stop_halos} halos, "
                      f"stop if avg > {threshold:.4f}", flush=True)
            else:
                print("NFW fitting failed, disabling NFW early stopping",
                      flush=True)
                use_nfw_early_stop = False

        results = []
        negative_loss_func_idx = set()
        asymp_reject_func_idx = set()
        asymp_pass_fractions = {}

        n_funcs = len(job_queue)
        t_start = time()
        total_fit_time = 0.0
        total_asymp_time = 0.0

        asymp_inf_threshold = fit_config.get('asymp_inf_threshold', 0.5)
        asymp_zero_threshold = fit_config.get('asymp_zero_threshold', 0.5)
        early_stop_threshold = fit_config.get('early_stop_failures', 5)

        for i, func_idx in enumerate(job_queue):
            t_func_start = time()
            expr_str = equations[func_idx]

            # Print progress
            print(f"[{i+1}/{n_funcs}] Fitting '{expr_str}'", flush=True)

            # Skip bad functions silently
            if cdmprof.fitting.is_bad_function(expr_str):
                continue

            try:
                fitter = cdmprof.compile_fitter(expr_str)
            except Exception as e:
                print(f"Failed to compile func {func_idx} '{expr_str}': {e}",
                      flush=True)
                continue

            func_results = []
            func_norm_losses = []  # Track normalized losses for NFW comparison
            n_negative_loss = 0
            n_consecutive_failures = 0
            early_stopped = False
            nfw_early_stopped = False

            t_fit_start = time()
            for halo_idx in range(n_halos):
                try:
                    result = fitter.fit_with_restarts(
                        binned['bin_counts'][halo_idx],
                        binned['bin_positions'][halo_idx],
                        binned['rmin'][halo_idx],
                        binned['rmax'][halo_idx],
                        max_restarts=fit_config['max_restarts'],
                        nconv_required=fit_config['nconv_required'],
                        conv_rtol=fit_config['conv_rtol'],
                        Rs_lower_factor=fit_config.get('Rs_lower_factor'),
                        Rs_upper_factor=fit_config.get('Rs_upper_factor'),
                        a_lower=fit_config.get('a_lower'),
                        a_upper=fit_config.get('a_upper'),
                        xtol=fit_config['xtol'],
                        ftol=fit_config['ftol'],
                        maxeval=fit_config['maxeval'],
                        seed=42 + halo_idx,
                    )

                    # Skip if fit failed (params is None)
                    if result['params'] is None:
                        if result.get('reject_reason') == 'negative_loss':
                            n_negative_loss += 1
                        # Track consecutive failures for early stopping
                        if len(func_results) == 0:
                            n_consecutive_failures += 1
                            if n_consecutive_failures >= early_stop_threshold:
                                early_stopped = True
                                break
                        continue

                    # Reset consecutive failures on success
                    n_consecutive_failures = 0

                    # Compute normalized loss for this halo
                    npart = np.sum(binned['bin_counts'][halo_idx])
                    norm_loss = result['loss'] / npart
                    func_norm_losses.append(norm_loss)

                    func_results.append((
                        func_idx, halo_idx, result['loss'],
                        result['params'], result['converged'], result['neval'],
                    ))

                    # NFW comparison early stopping
                    if (use_nfw_early_stop and
                            len(func_results) >= nfw_early_stop_halos):
                        func_avg = np.mean(func_norm_losses)
                        if func_avg > nfw_avg + nfw_early_stop_factor:
                            nfw_early_stopped = True
                            break

                except Exception as e:
                    print(f"Func {func_idx}, halo {halo_idx} failed: {e}",
                          flush=True)
                    # Track consecutive failures for early stopping
                    if len(func_results) == 0:
                        n_consecutive_failures += 1
                        if n_consecutive_failures >= early_stop_threshold:
                            early_stopped = True
                            break
            func_fit_time = time() - t_fit_start
            total_fit_time += func_fit_time
            func_asymp_time = 0.0

            if early_stopped:
                print(f"Func {func_idx} early stopped after "
                      f"{early_stop_threshold} failures", flush=True)
                continue

            if nfw_early_stopped:
                # Skip function entirely (don't save partial results)
                func_avg = np.mean(func_norm_losses)
                threshold = nfw_avg + nfw_early_stop_factor
                print(f"NFW early stopped '{expr_str}' "
                      f"(avg={func_avg:.4f} > {threshold:.4f})", flush=True)
                continue

            n_success = len(func_results)

            if n_success == 0:
                if n_negative_loss > 0:
                    negative_loss_func_idx.add(func_idx)
                    print(f"Func {func_idx} rejected (negative loss) "
                          f"'{expr_str}'", flush=True)
                else:
                    print(f"All fits failed for func {func_idx} '{expr_str}'",
                          flush=True)
            else:
                # Post-fit asymptote validation
                reject_asymp = False
                skip_asymp = fit_config.get('skip_postfit_asymp_check', False)
                has_inf_check = func_idx in asymp_inf_param_dep
                has_zero_check = func_idx in asymp_zero_param_dep
                has_unknown_check = func_idx in asymp_unknown
                needs_postfit_check = (has_inf_check or has_zero_check
                                       or has_unknown_check)

                if needs_postfit_check and not skip_asymp:
                    t_asymp_start = time()
                    reject_asymp, n_pass_inf, n_pass_zero, n_checked = \
                        check_postfit_asymptotes(
                            func_idx, expr_str, func_results, binned,
                            fit_config, asymp_inf_threshold,
                            asymp_zero_threshold, print_prefix="")
                    func_asymp_time = time() - t_asymp_start
                    total_asymp_time += func_asymp_time
                    asymp_pass_fractions[func_idx] = (
                        n_pass_inf, n_pass_zero, n_checked)

                if reject_asymp:
                    asymp_reject_func_idx.add(func_idx)
                    # Only skip results if rejection is enabled
                    if fit_config.get('reject_asymp_failures', True):
                        continue

                results.extend(func_results)

            # Write results after each function for resume support
            has_data = (len(results) > 0 or len(negative_loss_func_idx) > 0
                        or len(asymp_reject_func_idx) > 0)
            if has_data:
                temp_output = temp_dir / "results_rank0.hdf5"
                write_results(temp_output, results, equations,
                              negative_loss_func_idx, asymp_reject_func_idx,
                              asymp_pass_fractions)

            func_time = time() - t_func_start
            elapsed = time() - t_start
            funcs_done = i + 1
            avg_per_func = elapsed / funcs_done
            remaining = avg_per_func * (n_funcs - funcs_done)

            if remaining >= 3600:
                eta_str = f"{remaining / 3600:.1f} h"
            elif remaining >= 60:
                eta_str = f"{remaining / 60:.1f} min"
            else:
                eta_str = f"{remaining:.1f} s"

            print(f"Completed {funcs_done}/{n_funcs} | "
                  f"this: {func_time:.1f}s (fit={func_fit_time:.1f}, "
                  f"asymp={func_asymp_time:.1f}) | "
                  f"avg: {avg_per_func:.1f}s/func | ETA: {eta_str}",
                  flush=True)

        # Merge all results (including any from previous runs if resuming)
        merge_results(temp_dir, output_path, delete_rank_files=True)
        if temp_dir.exists():
            temp_dir.rmdir()
        print(f"All done! Results saved to: {output_path}", flush=True)

        # Print timing summary
        total_time = time() - t_start
        other_time = total_time - total_fit_time - total_asymp_time
        print("\nTiming breakdown:", flush=True)
        print(f"  Fitting:    {total_fit_time:8.1f}s "
              f"({100*total_fit_time/total_time:5.1f}%)", flush=True)
        print(f"  Asymptotes: {total_asymp_time:8.1f}s "
              f"({100*total_asymp_time/total_time:5.1f}%)", flush=True)
        print(f"  Other:      {other_time:8.1f}s "
              f"({100*other_time/total_time:5.1f}%)", flush=True)
        print(f"  Total:      {total_time:8.1f}s", flush=True)

        # Print failed functions
        print_failed_functions(output_path, equations)

        # Print asymptote validation summary
        n_param_dep = len(
            set(asymp_inf_param_dep.keys()) | set(asymp_zero_param_dep.keys()))
        n_unknown = len(asymp_unknown)
        n_rejected = len(asymp_reject_func_idx)
        print_asymptote_summary(n_param_dep, n_unknown, n_rejected,
                                asymp_inf_threshold, asymp_zero_threshold)

        # Compute npart per halo for ranking
        npart_per_halo = [np.sum(bc) for bc in binned['bin_counts']]
        # Functions that had post-fit asymptote checks
        asymp_postfit_funcs = (set(asymp_inf_param_dep.keys()) |
                               set(asymp_zero_param_dep.keys()) |
                               asymp_unknown)
        # Compute NFW reference score (reuse if already computed)
        if nfw_score is None:
            print("Computing NFW reference score...", flush=True)
            with warnings.catch_warnings():
                warnings.filterwarnings("ignore", message="reimporting")
                nfw_score = compute_nfw_scores(binned, fit_config)
        print_best_results(output_path, equations, npart_per_halo,
                           asymp_postfit_funcs, nfw_score)

    else:
        # Multi-process mode: master-worker pattern
        if rank == 0:
            asymp_n_halos = fit_config.get('asymp_n_halos', 10)
            if asymp_n_halos > 0:
                print(f"Asymptote checks: {asymp_n_halos} random halos",
                      flush=True)
            else:
                print("Asymptote checks: all halos", flush=True)

        # Compute NFW per-halo scores on rank 0 for early stopping comparison
        nfw_per_halo = None
        use_nfw_early_stop = fit_config.get('nfw_early_stop_enabled', False)
        nfw_early_stop_halos = fit_config.get('nfw_early_stop_halos', 5)
        nfw_early_stop_factor = fit_config.get('nfw_early_stop_factor', 2.0)
        if rank == 0 and use_nfw_early_stop:
            print("Computing NFW reference scores for early stopping...",
                  flush=True)
            with warnings.catch_warnings():
                warnings.filterwarnings("ignore", message="reimporting")
                _, nfw_per_halo = compute_nfw_scores(
                    binned, fit_config, return_per_halo=True)
            nfw_valid = (nfw_per_halo is not None
                         and np.any(~np.isnan(nfw_per_halo)))
            if nfw_valid:
                nfw_avg = np.nanmean(nfw_per_halo)
                print(f"NFW avg score: {nfw_avg:.4f}", flush=True)
                threshold = nfw_avg + nfw_early_stop_factor
                print(f"NFW early stop: after {nfw_early_stop_halos} halos, "
                      f"stop if avg > {threshold:.4f}", flush=True)
            else:
                print("NFW fitting failed, disabling NFW early stopping",
                      flush=True)
                nfw_per_halo = None

        # Broadcast NFW per-halo scores to all workers
        nfw_per_halo = comm.bcast(nfw_per_halo, root=0)

        if rank == 0:
            master_loop(comm, job_queue, fit_config['batch_size'])
        else:
            worker_loop(comm, equations, binned, temp_dir, fit_config,
                        asymp_inf_param_dep, asymp_zero_param_dep,
                        asymp_unknown, nfw_per_halo)

        comm.Barrier()

        if rank == 0:
            merge_results(temp_dir, output_path, delete_rank_files=True)
            if temp_dir.exists():
                temp_dir.rmdir()
            print(f"All done! Results saved to: {output_path}", flush=True)

            # Print failed functions
            print_failed_functions(output_path, equations)

            # Print asymptote validation summary
            n_param_dep = len(set(asymp_inf_param_dep.keys())
                              | set(asymp_zero_param_dep.keys()))
            n_unknown = len(asymp_unknown)
            # Read n_rejected from merged file
            with h5py.File(output_path, 'r') as f:
                if 'asymp_reject_func_idx' in f:
                    n_rejected = len(f['asymp_reject_func_idx'][:])
                else:
                    n_rejected = 0
            print_asymptote_summary(
                n_param_dep, n_unknown, n_rejected,
                fit_config.get('asymp_inf_threshold', 0.5),
                fit_config.get('asymp_zero_threshold', 0.5))

            # Compute npart per halo for ranking
            npart_per_halo = [np.sum(bc) for bc in binned['bin_counts']]
            # Functions that had post-fit asymptote checks
            asymp_postfit_funcs = (set(asymp_inf_param_dep.keys()) |
                                   set(asymp_zero_param_dep.keys()) |
                                   asymp_unknown)
            # Compute NFW reference score (reuse if already computed)
            print("Computing NFW reference score...", flush=True)
            with warnings.catch_warnings():
                warnings.filterwarnings("ignore", message="reimporting")
                nfw_score = compute_nfw_scores(binned, fit_config)
            print_best_results(output_path, equations, npart_per_halo,
                               asymp_postfit_funcs, nfw_score)
