# Copyright (C) 2025 Richard Stiskalek
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
"""
MPI script for fitting density profiles to halo data.

Uses dynamic work distribution (master-worker pattern) where rank 0
distributes batches of functions to worker ranks.
"""
import shutil
import warnings
from argparse import ArgumentParser
from datetime import datetime
from pathlib import Path
from time import time

import cdmprof
import h5py
import numpy as np
from mpi4py import MPI

from utils import (compute_function_scores, print_best_results,
                   print_failed_functions, read_config)

# MPI tags
WORK_TAG = 1
DONE_TAG = 0

# Maximum number of parameters to store (for fixed-size HDF5 datasets)
MAX_NPARAMS = 10


def _timestamp():
    """Return current time as ``[HH:MM:SS]`` string."""
    return datetime.now().strftime("[%H:%M:%S]")


def format_time(seconds):
    """Format time in appropriate units (s, min, or h)."""
    if seconds >= 3600:
        return f"{seconds / 3600:.1f}h"
    elif seconds >= 60:
        return f"{seconds / 60:.1f}m"
    else:
        return f"{seconds:.1f}s"


def get_param_dependent_value(config_value, nfree):
    """
    Get a config value that depends on the number of free parameters.

    If config_value is a list, returns the value at index (nfree - 1),
    or the last value if nfree exceeds the list length.
    If config_value is a scalar, returns it directly.
    """
    if isinstance(config_value, list):
        idx = min(nfree - 1, len(config_value) - 1)
        return config_value[max(0, idx)]
    return config_value


def load_skip_functions(skip_path):
    """
    Load skip file generated by generate_functions.py.

    File format: `idx reason equation`

    Parameters
    ----------
    skip_path : Path
        Path to skip_functions_{comp}.txt file.

    Returns
    -------
    dict
        Dictionary mapping func_idx -> reason for skipping.
    """
    skip_path = Path(skip_path)
    skip_dict = {}

    if not skip_path.exists():
        return skip_dict

    with open(skip_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            # Format: idx reason equation
            parts = line.split(maxsplit=2)
            if len(parts) >= 2:
                idx, reason = parts[0], parts[1]
                skip_dict[int(idx)] = reason

    return skip_dict


def clear_temp_dir(temp_dir):
    """
    Remove all files in temp directory and the directory itself.

    Parameters
    ----------
    temp_dir : Path
        Directory to clear.
    """
    temp_dir = Path(temp_dir)
    if not temp_dir.exists():
        return

    for fpath in temp_dir.glob("*"):
        fpath.unlink()

    temp_dir.rmdir()


def write_ranking_to_file(output_path, equations, npart_per_halo,
                          nfw_score=None, nfw_bic=None, txt_path=None,
                          min_success_fraction=0.0,
                          failure_loss_percentile=0):
    """Write ranking of best functions to a text file."""
    output_path = Path(output_path)
    if not output_path.exists():
        return

    # Check if there are any results
    with h5py.File(output_path, 'r') as f:
        if 'func_idx' not in f:
            print("No successful fits - skipping ranking file.")
            return

    if txt_path is None:
        txt_path = output_path.with_suffix('.txt')
    else:
        txt_path = Path(txt_path)

    scores, asymp_pass_dict, n_halos_total, n_filtered = \
        compute_function_scores(output_path, npart_per_halo,
                                min_success_fraction, failure_loss_percentile)

    # Find best BIC for dBIC computation
    if scores:
        best_bic = min(s[2] for s in scores)
    else:
        best_bic = 0

    with open(txt_path, 'w') as f:
        f.write("# Best functions ranked by avg loss/npart per halo\n")
        f.write("# Lower score is better\n")
        f.write("# dBIC = BIC - BIC_best; BIC = k*ln(n) + 2*loss\n")
        if failure_loss_percentile > 0:
            f.write(f"# Failed halos imputed with p{failure_loss_percentile} "
                    f"of successful fits\n")
        f.write(f"# Total functions: {len(scores)}\n")
        f.write(f"# Total halos: {n_halos_total}\n")
        if n_filtered > 0:
            min_halos = int(min_success_fraction * n_halos_total)
            f.write(f"# Filtered out: {n_filtered} functions "
                    f"(< {min_halos} successful fits)\n")
        if nfw_score is not None:
            nfw_str = f"# NFW reference: score={nfw_score:.6f}"
            if nfw_bic is not None:
                nfw_str += f", dBIC={nfw_bic - best_bic:.6f}"
            f.write(nfw_str + "\n")
        f.write("#\n")
        f.write("# Columns: rank, func_idx, avg_score, dBIC, nparams, "
                "n_halos, asymp_inf%, asymp_zero%, equation\n")
        f.write("#\n")

        for rank, (fidx, score, bic, nparams, n_halos) in enumerate(scores, 1):
            eq = equations[fidx]
            dbic = bic - best_bic
            if fidx in asymp_pass_dict:
                n_inf, n_zero, n_total = asymp_pass_dict[fidx]
                if n_total > 0:
                    pct_inf = 100 * n_inf / n_total
                    pct_zero = 100 * n_zero / n_total
                else:
                    pct_inf, pct_zero = -1, -1
            else:
                pct_inf, pct_zero = -1, -1

            f.write(f"{rank}\t{fidx}\t{score:.6f}\t{dbic:.1f}\t{nparams}\t"
                    f"{n_halos}\t{pct_inf:.0f}\t{pct_zero:.0f}\t{eq}\n")

    print(f"Ranking saved to: {txt_path}")


def write_failed_to_files(output_path, categories, output_dir=None):
    """Write failed/skipped functions to separate text files by category."""
    output_path = Path(output_path)

    if output_dir is None:
        output_dir = output_path.parent
    else:
        output_dir = Path(output_dir)

    base_name = output_path.stem
    n_failed = sum(len(v) for v in categories.values())
    if n_failed == 0:
        return

    descriptions = {
        'negative_loss': 'Negative loss (numerical issues/singularities)',
        'asymptote': 'Failed post-fit asymptote validation',
        'normalization_only': 'Normalization-only parameter (pre-skipped)',
        'bad_function': 'Bad function - contains nan/inf/trig (pre-skipped)',
        'asymp_prefit': 'Pre-fit asymptote check failed (pre-skipped)',
        'other': 'Other failures (compilation/fit errors)',
    }

    files_written = []
    for cat_name, cat_list in categories.items():
        if len(cat_list) == 0:
            continue

        fpath = output_dir / f"{base_name}_failed_{cat_name}.txt"
        with open(fpath, 'w') as f:
            f.write(f"# {descriptions.get(cat_name, cat_name)}\n")
            f.write(f"# Count: {len(cat_list)}\n")
            f.write("# Columns: func_idx, equation\n")
            f.write("#\n")
            for fidx, eq in cat_list:
                f.write(f"{fidx}\t{eq}\n")

        files_written.append(fpath)

    if len(files_written) > 0:
        print(f"Failed functions saved to {len(files_written)} files:")
        for fpath in files_written:
            print(f"  {fpath}")


def compute_nfw_scores(binned, fit_config, return_per_halo=False):
    """
    Compute the NFW reference score for comparison.

    NFW profile: rho(x) = 1 / (x * (1 + x)^2)

    Parameters
    ----------
    binned : dict
        Binned halo data from HaloCollection.bin().
    fit_config : dict
        Fitting configuration parameters.
    return_per_halo : bool, optional
        If True, also return per-halo normalized losses.

    Returns
    -------
    avg_score : float or None
        NFW score (avg of loss/npart), or None if fitting fails.
    avg_bic : float or None
        NFW BIC score (avg of BIC/npart), or None if fitting fails.
    per_halo_scores : np.ndarray or None (only if return_per_halo=True)
        Per-halo loss/npart values (nan for failed fits).
    """
    nfw_expr = "1 / (x * (1 + x)**2)"

    try:
        fitter = cdmprof.compile_fitter(nfw_expr)
    except Exception as e:
        print(f"Failed to compile NFW profile: {e}", flush=True)
        if return_per_halo:
            return None, None, None
        return None, None

    nhalo = len(binned['halo_ids'])
    total_score = 0.0
    total_bic = 0.0
    n_success = 0
    per_halo_scores = np.full(nhalo, np.nan)
    nparams = fitter.nparams  # NFW has 1 param (Rs)

    for halo_idx in range(nhalo):
        try:
            result = fitter.fit_with_restarts(
                binned['bin_counts'][halo_idx],
                binned['bin_positions'][halo_idx],
                binned['rmin'][halo_idx],
                binned['rmax'][halo_idx],
                max_restarts=get_param_dependent_value(
                    fit_config['max_restarts'], fitter.nfree),
                nconv_required=get_param_dependent_value(
                    fit_config['nconv_required'], fitter.nfree),
                conv_rtol=fit_config['conv_rtol'],
                Rs_lower_factor=fit_config.get('Rs_lower_factor'),
                Rs_upper_factor=fit_config.get('Rs_upper_factor'),
                a_lower=fit_config.get('a_lower'),
                a_upper=fit_config.get('a_upper'),
                xtol=fit_config['xtol'],
                ftol=fit_config['ftol'],
                maxeval=fit_config['maxeval'],
                seed=42 + halo_idx,
                optimizer=fit_config.get('optimizer', 'neldermead'),
            )

            if result['params'] is not None:
                npart = np.sum(binned['bin_counts'][halo_idx])
                norm_loss = result['loss'] / npart
                # BIC = k * ln(n) + 2 * loss
                bic = nparams * np.log(npart) + 2 * result['loss']
                norm_bic = bic / npart
                total_score += norm_loss
                total_bic += norm_bic
                per_halo_scores[halo_idx] = norm_loss
                n_success += 1
        except Exception:
            pass

    if n_success == 0:
        if return_per_halo:
            return None, None, None
        return None, None

    # Penalize for missing halos
    if n_success < nhalo:
        mean_score = total_score / n_success
        mean_bic = total_bic / n_success
        total_score += (nhalo - n_success) * mean_score
        total_bic += (nhalo - n_success) * mean_bic

    # Convert to per-halo average
    avg_score = total_score / nhalo
    avg_bic = total_bic / nhalo

    if return_per_halo:
        return avg_score, avg_bic, per_halo_scores
    return avg_score, avg_bic


def setup_nfw_early_stop(fit_config, nfw_per_halo=None):
    """
    Parse NFW early stop configuration and compute reference values.

    Parameters
    ----------
    fit_config : dict
        Fitting configuration dictionary.
    nfw_per_halo : np.ndarray, optional
        Per-halo NFW normalized losses. If None, early stopping is disabled.

    Returns
    -------
    dict
        Configuration dict with keys:
        - 'enabled': bool, whether early stopping is active
        - 'tiers': list of (n_halos, factor) tuples
        - 'same_halos': bool, compare against same halos or all
        - 'avg_all': float or None, NFW average over all halos
    """
    halos_list = fit_config.get('nfw_early_stop_halos', [])
    factors_list = fit_config.get('nfw_early_stop_factors', [])
    tiers = [(h, f) for h, f in zip(halos_list, factors_list) if h > 0]
    same_halos = fit_config.get('nfw_early_stop_same_halos', True)

    # Check if early stopping should be enabled
    has_valid_nfw = (nfw_per_halo is not None
                     and np.any(~np.isnan(nfw_per_halo)))
    enabled = (fit_config.get('nfw_early_stop_enabled', False)
               and has_valid_nfw
               and len(tiers) > 0)

    avg_all = np.nanmean(nfw_per_halo) if enabled else None

    return {
        'enabled': enabled,
        'tiers': tiers,
        'same_halos': same_halos,
        'avg_all': avg_all,
    }


def fit_function_to_halos(func_idx, fitter, binned, fit_config,
                          nfw_config, nfw_per_halo, log_prefix=""):
    """
    Fit a compiled function to all halos.

    Parameters
    ----------
    func_idx : int
        Function index for result tuples.
    fitter : object
        Compiled fitter from cdmprof.compile_fitter().
    binned : dict
        Binned halo data with 'bin_counts', 'bin_positions', 'rmin', 'rmax'.
    fit_config : dict
        Fitting configuration dictionary.
    nfw_config : dict
        NFW early stop configuration from setup_nfw_early_stop().
    nfw_per_halo : np.ndarray or None
        Per-halo NFW normalized losses for comparison.
    log_prefix : str, optional
        Prefix for log messages (e.g., "Rank 0: ").

    Returns
    -------
    dict
        Results dict with keys:
        - 'results': list of (func_idx, halo_idx, loss, params, converged,
            neval)
        - 'n_negative_loss': int, count of negative loss rejections
        - 'early_stopped': bool, stopped due to consecutive failures
        - 'nfw_early_stopped': bool, stopped due to NFW comparison
        - 'nfw_avg': float or None, NFW average used in last comparison
    """
    nhalo = len(binned['halo_ids'])
    early_stop_threshold = fit_config.get('early_stop_failures', 5)

    func_results = []
    func_norm_losses = []
    n_negative_loss = 0
    n_consecutive_failures = 0
    early_stopped = False
    nfw_early_stopped = False
    nfw_avg = None

    for halo_idx in range(nhalo):
        try:
            result = fitter.fit_with_restarts(
                binned['bin_counts'][halo_idx],
                binned['bin_positions'][halo_idx],
                binned['rmin'][halo_idx],
                binned['rmax'][halo_idx],
                max_restarts=get_param_dependent_value(
                    fit_config['max_restarts'], fitter.nfree),
                nconv_required=get_param_dependent_value(
                    fit_config['nconv_required'], fitter.nfree),
                conv_rtol=fit_config['conv_rtol'],
                conv_atol=fit_config.get('conv_atol', 10),
                Rs_lower_factor=fit_config.get('Rs_lower_factor'),
                Rs_upper_factor=fit_config.get('Rs_upper_factor'),
                a_lower=fit_config.get('a_lower'),
                a_upper=fit_config.get('a_upper'),
                xtol=fit_config['xtol'],
                ftol=fit_config['ftol'],
                maxeval=fit_config['maxeval'],
                seed=42 + halo_idx,
                optimizer=fit_config.get('optimizer', 'neldermead'),
            )

            # Skip if fit failed (params is None)
            if result['params'] is None:
                if result.get('reject_reason') == 'negative_loss':
                    n_negative_loss += 1
                # Track consecutive failures for early stopping
                if len(func_results) == 0:
                    n_consecutive_failures += 1
                    if n_consecutive_failures >= early_stop_threshold:
                        early_stopped = True
                        break
                continue

            # Reset consecutive failures on success
            n_consecutive_failures = 0

            # Compute normalized loss for this halo
            npart = np.sum(binned['bin_counts'][halo_idx])
            norm_loss = result['loss'] / npart
            func_norm_losses.append(norm_loss)

            func_results.append((
                func_idx,
                halo_idx,
                result['loss'],
                result['params'],
                result['converged'],
                result['neval'],
            ))

            # NFW comparison early stopping (multi-tier)
            if nfw_config['enabled']:
                n_fitted = len(func_results)
                func_avg = np.mean(func_norm_losses)
                # Compare against same halos or all halos
                if nfw_config['same_halos']:
                    nfw_avg = np.nanmean(nfw_per_halo[:halo_idx + 1])
                else:
                    nfw_avg = nfw_config['avg_all']
                for tier_halos, tier_factor in nfw_config['tiers']:
                    if (n_fitted >= tier_halos and
                            func_avg > nfw_avg + tier_factor):
                        nfw_early_stopped = True
                        break
                if nfw_early_stopped:
                    break

        except Exception as e:
            print(f"{_timestamp()} {log_prefix}func {func_idx}, "
                  f"halo {halo_idx} failed: {e}", flush=True)
            # Track consecutive failures for early stopping
            if len(func_results) == 0:
                n_consecutive_failures += 1
                if n_consecutive_failures >= early_stop_threshold:
                    early_stopped = True
                    break

    return {
        'results': func_results,
        'n_negative_loss': n_negative_loss,
        'early_stopped': early_stopped,
        'nfw_early_stopped': nfw_early_stopped,
        'nfw_avg': nfw_avg,
    }


class ResultsFile:
    """
    HDF5 results file handler for fit results.

    Provides methods for reading, writing, appending, and merging results.
    """

    # Core result dataset names
    RESULT_FIELDS = ['func_idx', 'halo_idx', 'loss', 'params', 'nparams',
                     'converged', 'neval']
    # Asymptote pass fraction field names
    ASYMP_PASS_FIELDS = ['asymp_pass_func_idx', 'asymp_pass_inf',
                         'asymp_pass_zero', 'asymp_pass_total']

    def __init__(self, path):
        self.path = Path(path)

    def exists(self):
        return self.path.exists()

    # -------------------------------------------------------------------------
    # Helper methods for reading/writing
    # -------------------------------------------------------------------------

    @staticmethod
    def _read_index_set(f, name):
        """Read an index set from HDF5 file."""
        if name in f:
            return set(f[name][:].tolist())
        return set()

    @staticmethod
    def _write_index_set(f, name, data):
        """Write an index set to HDF5 file (replaces existing)."""
        if name in f:
            del f[name]
        if data:
            arr = np.array(sorted(data), dtype=np.int32)
            f.create_dataset(name, data=arr)

    @staticmethod
    def _read_asymp_pass(f):
        """Read asymptote pass fractions -> dict."""
        if 'asymp_pass_func_idx' not in f:
            return {}
        idx = f['asymp_pass_func_idx'][:]
        inf = f['asymp_pass_inf'][:]
        zero = f['asymp_pass_zero'][:]
        total = f['asymp_pass_total'][:]
        return {int(idx[i]): (int(inf[i]), int(zero[i]), int(total[i]))
                for i in range(len(idx))}

    @staticmethod
    def _write_asymp_pass(f, data):
        """Write asymptote pass fractions from dict (replaces existing)."""
        for name in ResultsFile.ASYMP_PASS_FIELDS:
            if name in f:
                del f[name]
        if not data:
            return
        n = len(data)
        idx = np.zeros(n, dtype=np.int32)
        inf = np.zeros(n, dtype=np.int32)
        zero = np.zeros(n, dtype=np.int32)
        total = np.zeros(n, dtype=np.int32)
        items = sorted(data.items())
        for i, (fidx, (n_inf, n_zero, n_tot)) in enumerate(items):
            idx[i], inf[i], zero[i], total[i] = fidx, n_inf, n_zero, n_tot
        f.create_dataset('asymp_pass_func_idx', data=idx)
        f.create_dataset('asymp_pass_inf', data=inf)
        f.create_dataset('asymp_pass_zero', data=zero)
        f.create_dataset('asymp_pass_total', data=total)

    # -------------------------------------------------------------------------
    # Public methods
    # -------------------------------------------------------------------------

    def append(self, new_results, equations, negative_loss_func_idx=None,
               processed_func_idx=None, nfw_score=None):
        """
        Append fit results to file, creating it if needed.

        Parameters
        ----------
        new_results : list of tuples
            Each tuple: (func_idx, halo_idx, loss, params, converged, neval)
        equations : list of str
            Equation strings (written once on creation).
        negative_loss_func_idx : set, optional
            Functions rejected due to negative loss.
        processed_func_idx : set, optional
            All attempted function indices.
        nfw_score : float, optional
            NFW reference score.
        """
        negative_loss_func_idx = negative_loss_func_idx or set()
        processed_func_idx = processed_func_idx or set()

        no_data = (len(new_results) == 0 and not negative_loss_func_idx
                   and not processed_func_idx)
        if no_data and not self.exists():
            return

        # Prepare result arrays
        if len(new_results) > 0:
            arrays = {
                'func_idx': np.array([r[0] for r in new_results], np.int32),
                'halo_idx': np.array([r[1] for r in new_results], np.int32),
                'loss': np.array([r[2] for r in new_results], np.float64),
                'converged': np.array([r[4] for r in new_results], np.int32),
                'neval': np.array([r[5] for r in new_results], np.int32),
            }
            # Pad params to fixed size and store nparams
            params = np.full((len(new_results), MAX_NPARAMS), np.nan,
                             dtype=np.float64)
            nparams = np.zeros(len(new_results), dtype=np.int32)
            for i, r in enumerate(new_results):
                n = min(len(r[3]), MAX_NPARAMS)
                params[i, :n] = r[3][:n]
                nparams[i] = len(r[3])
            arrays['params'] = params
            arrays['nparams'] = nparams

        mode = 'a' if self.exists() else 'w'
        with h5py.File(self.path, mode) as f:
            # Append/create result datasets
            if len(new_results) > 0:
                if 'func_idx' in f:
                    for name, data in arrays.items():
                        dset = f[name]
                        old_size = dset.shape[0]
                        dset.resize(old_size + len(data), axis=0)
                        dset[old_size:] = data
                else:
                    for name, data in arrays.items():
                        maxshape = (None, MAX_NPARAMS) if name == 'params' \
                            else (None,)
                        f.create_dataset(name, data=data, maxshape=maxshape,
                                         chunks=True)

            # Write equations once
            if 'equations' not in f:
                dt = h5py.special_dtype(vlen=str)
                f.create_dataset('equations', data=np.array(equations,
                                 dtype=object), dtype=dt)

            # Merge and write metadata
            merged_neg = self._read_index_set(f, 'negative_loss_func_idx')
            merged_neg |= negative_loss_func_idx
            self._write_index_set(f, 'negative_loss_func_idx', merged_neg)

            merged_proc = self._read_index_set(f, 'processed_func_idx')
            merged_proc |= processed_func_idx
            self._write_index_set(f, 'processed_func_idx', merged_proc)

            if nfw_score is not None:
                f.attrs['nfw_score'] = nfw_score

    @classmethod
    def merge(cls, input_dir, output_path, delete_rank_files=True,
              append_to_existing=False, npart_per_halo=None):
        """
        Merge results_rank*.hdf5 files into a single output file.

        Parameters
        ----------
        input_dir : Path
            Directory containing results_rank*.hdf5 files.
        output_path : Path
            Output file path.
        delete_rank_files : bool
            Delete input files after merging.
        append_to_existing : bool
            Append to existing output file.
        npart_per_halo : array-like, optional
            If provided, clear params for functions worse than NFW.

        Returns
        -------
        int
            Total number of results merged.
        """
        input_dir = Path(input_dir)
        output_path = Path(output_path)

        rank_files = sorted(input_dir.glob("results_rank*.hdf5"))
        if not rank_files:
            print(f"No results_rank*.hdf5 files found in {input_dir}")
            return 0

        print(f"Merging {len(rank_files)} rank files...", flush=True)

        # Collect all data
        all_results = {name: [] for name in cls.RESULT_FIELDS}
        all_neg_loss = set()
        all_asymp_reject = set()
        all_asymp_pass = {}
        all_processed = set()
        nfw_score = None
        equations = None

        # Source files: existing output (if appending) + rank files
        source_files = []
        if append_to_existing and output_path.exists():
            print(f"Appending to existing output: {output_path}", flush=True)
            source_files.append(output_path)
        source_files.extend(rank_files)

        for fpath in source_files:
            with h5py.File(fpath, 'r') as f:
                # Read result arrays
                if 'func_idx' in f:
                    for name in cls.RESULT_FIELDS:
                        all_results[name].append(f[name][:])

                # Read equations (first found)
                if equations is None and 'equations' in f:
                    equations = f['equations'][:]

                # Read metadata
                all_neg_loss |= cls._read_index_set(
                    f, 'negative_loss_func_idx')
                all_asymp_reject |= cls._read_index_set(
                    f, 'asymp_reject_func_idx')
                all_asymp_pass.update(cls._read_asymp_pass(f))
                all_processed |= cls._read_index_set(
                    f, 'processed_func_idx')

                if nfw_score is None and 'nfw_score' in f.attrs:
                    nfw_score = f.attrs['nfw_score']

        if not all_results['func_idx'] and not all_processed:
            print("No data to merge")
            return 0

        # Concatenate results
        has_results = len(all_results['func_idx']) > 0
        if has_results:
            # Pad params arrays to same width
            max_ncols = max(p.shape[1] for p in all_results['params'])
            padded = []
            for p in all_results['params']:
                if p.shape[1] < max_ncols:
                    p = np.pad(p, ((0, 0), (0, max_ncols - p.shape[1])),
                               constant_values=np.nan)
                padded.append(p)
            all_results['params'] = padded

            merged = {name: np.concatenate(all_results[name])
                      for name in cls.RESULT_FIELDS}

            n_total = len(merged['func_idx'])
            n_funcs = len(np.unique(merged['func_idx']))
            n_halos = len(np.unique(merged['halo_idx']))

            # Filter params for functions worse than NFW
            if npart_per_halo is not None and nfw_score is not None:
                npart = np.asarray(npart_per_halo)
                norm_loss = merged['loss'] / npart[merged['halo_idx']]
                unique_f, inv, counts = np.unique(
                    merged['func_idx'], return_inverse=True,
                    return_counts=True)
                sums = np.bincount(inv, weights=norm_loss)
                means = sums / counts
                n_miss = len(npart) - counts
                penalty = np.where(n_miss > 0, n_miss * means, 0.0)
                scores = (sums + penalty) / len(npart)

                good = set(unique_f[scores <= nfw_score])
                n_bad = len(unique_f) - len(good)
                print(f"Params filter: {len(good)} functions <= NFW, "
                      f"{n_bad} functions > NFW (params cleared)", flush=True)
                bad_mask = ~np.isin(merged['func_idx'], list(good))
                merged['params'][bad_mask] = np.nan
        else:
            merged = None
            n_total = n_funcs = n_halos = 0

        # Write output
        with h5py.File(output_path, 'w') as f:
            if has_results:
                for name in cls.RESULT_FIELDS:
                    if name == 'params':
                        f.create_dataset(
                            name, data=merged[name],
                            compression='gzip', compression_opts=4)
                    else:
                        f.create_dataset(name, data=merged[name])

            if equations is not None:
                dt = h5py.special_dtype(vlen=str)
                f.create_dataset('equations', data=equations, dtype=dt)

            cls._write_index_set(f, 'negative_loss_func_idx', all_neg_loss)
            cls._write_index_set(f, 'asymp_reject_func_idx', all_asymp_reject)
            cls._write_asymp_pass(f, all_asymp_pass)
            cls._write_index_set(f, 'processed_func_idx', all_processed)

            if nfw_score is not None:
                f.attrs['nfw_score'] = nfw_score
            f.attrs['n_results'] = n_total
            f.attrs['n_functions'] = n_funcs
            f.attrs['n_halos'] = n_halos

        # Print summary
        n_proc = len(all_processed)
        print(f"Merged {n_total} results ({n_funcs} functions, "
              f"{n_halos} halos, {n_proc} processed)", flush=True)
        if all_neg_loss:
            print(f"  {len(all_neg_loss)} functions rejected (negative loss)",
                  flush=True)
        if all_asymp_reject:
            print(f"  {len(all_asymp_reject)} functions rejected "
                  f"(asymptote validation)", flush=True)
        print(f"Wrote merged results to {output_path}", flush=True)

        if delete_rank_files:
            for fpath in rank_files:
                fpath.unlink()

        return n_total


def master_loop(comm, job_queue, batch_size):
    """
    Master process: distribute work to workers.

    Parameters
    ----------
    comm : MPI.Comm
        MPI communicator.
    job_queue : list of int
        List of func_idx to process.
    batch_size : int
        Number of functions per batch.
    """
    size = comm.Get_size()
    n_workers = size - 1

    job_queue = list(job_queue)  # Make a copy
    n_total = len(job_queue)
    workers_done = 0

    print(f"{_timestamp()} Master: {n_total} functions to process, "
          f"{n_workers} workers, batch size {batch_size}", flush=True)

    while workers_done < n_workers:
        # Wait for any worker to request work
        status = MPI.Status()
        worker_rank = comm.recv(source=MPI.ANY_SOURCE, tag=MPI.ANY_TAG,
                                status=status)

        if len(job_queue) > 0:
            # Send next batch
            batch = job_queue[:batch_size]
            job_queue = job_queue[batch_size:]
            comm.send(batch, dest=worker_rank, tag=WORK_TAG)
            print(f"{_timestamp()} Master: sent {len(batch)} jobs to "
                  f"rank {worker_rank}, {len(job_queue)} remaining",
                  flush=True)
        else:
            # No more work, tell worker to finish
            comm.send(None, dest=worker_rank, tag=DONE_TAG)
            workers_done += 1
            print(f"{_timestamp()} Master: rank {worker_rank} done, "
                  f"{n_workers - workers_done} workers remaining", flush=True)


def worker_loop(comm, equations, binned, output_dir, fit_config,
                nfw_per_halo=None, nfw_score=None):
    """
    Worker process: request work, fit functions, save results.

    Parameters
    ----------
    comm : MPI.Comm
        MPI communicator.
    equations : list of str
        List of equations.
    binned : dict
        Binned halo data from HaloCollection.bin().
    output_dir : Path
        Output directory.
    fit_config : dict
        Fitting configuration parameters.
    nfw_per_halo : np.ndarray, optional
        Per-halo NFW normalized losses for early stopping comparison.
    nfw_score : float, optional
        NFW reference score.
    """
    rank = comm.Get_rank()
    output_path = output_dir / f"results_rank{rank}.hdf5"

    # Buffer for results - cleared after each write
    results_buffer = []
    total_results_written = 0

    negative_loss_func_idx = set()
    processed_func_idx = set()  # Track all attempted functions

    # Timing tracking
    total_fit_time = 0.0
    t_worker_start = time()

    # NFW comparison settings (multi-tier early stopping)
    nfw_config = setup_nfw_early_stop(fit_config, nfw_per_halo)
    early_stop_threshold = fit_config.get('early_stop_failures', 5)

    while True:
        # Request work from master
        comm.send(rank, dest=0)

        # Receive response
        status = MPI.Status()
        batch = comm.recv(source=0, tag=MPI.ANY_TAG, status=status)

        if status.tag == DONE_TAG:
            break

        # Process batch of functions
        t_batch_start = time()
        n_funcs_batch = len(batch)

        for func_idx in batch:
            expr_str = equations[func_idx]

            # Mark as processed regardless of outcome
            processed_func_idx.add(func_idx)

            # Skip bad functions silently
            if cdmprof.fitting.is_bad_function(expr_str):
                continue

            try:
                fitter = cdmprof.compile_fitter(expr_str)
            except Exception as e:
                print(f"{_timestamp()} Rank {rank}: failed to compile "
                      f"func {func_idx} '{expr_str}': {e}", flush=True)
                continue

            # Fit to all halos
            t_fit_start = time()
            fit_result = fit_function_to_halos(
                func_idx, fitter, binned, fit_config,
                nfw_config, nfw_per_halo,
                log_prefix=f"Rank {rank}: ")
            total_fit_time += time() - t_fit_start

            # Handle early stopping
            if fit_result['early_stopped']:
                print(f"{_timestamp()} Rank {rank}: func {func_idx} "
                      f"early stopped after "
                      f"{early_stop_threshold} failures", flush=True)
                continue

            if fit_result['nfw_early_stopped']:
                n_fitted = len(fit_result['results'])
                func_avg = np.mean([r[2] / np.sum(binned['bin_counts'][r[1]])
                                    for r in fit_result['results']])
                print(f"{_timestamp()} Rank {rank}: NFW early stopped "
                      f"'{expr_str}' (n={n_fitted}, avg={func_avg:.4f}, "
                      f"nfw={fit_result['nfw_avg']:.4f})", flush=True)
                continue

            # Check if function should be rejected
            n_success = len(fit_result['results'])

            if n_success == 0:
                if fit_result['n_negative_loss'] > 0:
                    negative_loss_func_idx.add(func_idx)
                    print(f"{_timestamp()} Rank {rank}: func {func_idx}"
                          f" rejected (negative loss) '{expr_str}'",
                          flush=True)
                else:
                    print(f"{_timestamp()} Rank {rank}: all fits failed"
                          f" for func {func_idx} '{expr_str}'",
                          flush=True)
                continue

            results_buffer.extend(fit_result['results'])

        batch_time = time() - t_batch_start
        avg_per_func = batch_time / n_funcs_batch if n_funcs_batch > 0 else 0

        # Write results after each batch for resume support
        has_data = (len(results_buffer) > 0 or len(negative_loss_func_idx) > 0
                    or len(processed_func_idx) > 0)
        if has_data:
            ResultsFile(output_path).append(
                results_buffer, equations, negative_loss_func_idx,
                processed_func_idx, nfw_score)
            total_results_written += len(results_buffer)
            results_buffer = []  # Clear buffer after writing

        print(f"{_timestamp()} Rank {rank}: "
              f"{n_funcs_batch} funcs in {batch_time:.1f}s | "
              f"{avg_per_func:.1f}s/func | {total_results_written} total",
              flush=True)

    total_worker_time = time() - t_worker_start
    print(f"{_timestamp()} Rank {rank}: finished with "
          f"{total_results_written} total results", flush=True)

    # Return timing data for aggregation
    return total_fit_time, total_worker_time


if __name__ == "__main__":
    # Load config first for defaults
    config = read_config()
    fit_config = config['fitting']

    parser = ArgumentParser(description="Fit density profiles with MPI")
    parser.add_argument("--complexity", type=int, required=True,
                        help="Equation complexity level")
    parser.add_argument("--snap", type=int, default=99,
                        help="Snapshot number (default: 99)")
    parser.add_argument("--halos", type=str, default=None,
                        help="Path to halo data (overrides config)")
    parser.add_argument("--resume", action="store_true",
                        help="Resume from existing results in temp directory")
    args = parser.parse_args()

    # Resolve halos path: command line > config
    if args.halos is not None:
        halos_input = args.halos
    else:
        halos_input = fit_config.get('halos')
        if halos_input is None:
            raise ValueError("No halos path specified. Use --halos or set "
                             "fitting.halos in config.toml")
        # Format snapshot placeholder if present
        halos_input = halos_input.format(snap=args.snap)
        # Resolve relative to data directory from local_config
        data_dir = Path(config['path'].get('data', '.'))
        halos_input = str(data_dir / halos_input)

    # Construct equations path from config
    runname = fit_config['runname']
    results_base = Path(config['path']['results'])
    equations_dir = results_base / runname / f"compl_{args.complexity}"
    equations_path = equations_dir / f"unique_equations_{args.complexity}.txt"
    skip_path = equations_dir / f"skip_functions_{args.complexity}.txt"
    asymp_inf_path = equations_dir / f"asymptotes_inf_{args.complexity}.txt"
    asymp_zero_path = equations_dir / f"asymptotes_zero_{args.complexity}.txt"

    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    size = comm.Get_size()

    # Derive output filename from halos path, runname, and complexity
    halos_path = Path(halos_input)
    if halos_path.suffix in ['.hdf5', '.h5']:
        halos_name = halos_path.stem  # Use filename without extension
    else:
        halos_name = halos_path.name  # Use folder name
    output_fname = f"fit_{runname}_compl{args.complexity}_{halos_name}.hdf5"
    output_path = results_base / output_fname

    # Temp directory for rank files (not hidden)
    temp_dir_name = f"tmp_fit_{runname}_compl{args.complexity}_{halos_name}"
    temp_dir = results_base / temp_dir_name

    # Per-job CFFI cache directory to avoid .so collisions between
    # concurrent jobs (different complexity levels or snapshots).
    cffi_cache_name = (f"cffi_cache_{runname}"
                       f"_compl{args.complexity}_{halos_name}")
    cffi_cache = results_base / cffi_cache_name
    cffi_cache.mkdir(parents=True, exist_ok=True)
    cdmprof.fitting.CFFI_TMPDIR = cffi_cache
    cdmprof.symbolic.CFFI_TMPDIR = cffi_cache

    # Load equations (all ranks)
    equations = cdmprof.fitting.load_equations(equations_path)

    # Load skip file and asymptotes (pre-computed invalid functions)
    skip_func_idx = set()
    asymp_inf_param_dep = {}
    asymp_zero_param_dep = {}
    asymp_unknown = set()
    if rank == 0:
        # Load validation skip file
        skip_dict = load_skip_functions(skip_path)
        skip_func_idx = set(skip_dict.keys())

        # Skip functions with 're(' operator
        # (sympy real part, not C99 compilable)
        for idx, eq in enumerate(equations):
            if 're(' in eq and idx not in skip_dict:
                skip_dict[idx] = "re_operator"
                skip_func_idx.add(idx)

        # Load asymptotes and add pre-fit skips
        (asymp_skip, asymp_inf_param_dep,
         asymp_zero_param_dep, asymp_unknown) = \
            cdmprof.asymptotes.process_asymptotes(asymp_inf_path,
                                                  asymp_zero_path)

        # Merge asymptote skips into skip_dict
        for idx, reason in asymp_skip.items():
            if idx not in skip_dict:
                skip_dict[idx] = reason
                skip_func_idx.add(idx)

        if len(skip_func_idx) > 0:
            print(f"Skipping {len(skip_func_idx)} pre-flagged functions:",
                  flush=True)
            # Count by reason
            reasons = {}
            for reason in skip_dict.values():
                reasons[reason] = reasons.get(reason, 0) + 1
            for reason, count in sorted(reasons.items()):
                print(f"  {reason}: {count}", flush=True)

        # Print param-dep and unknown asymptote counts
        n_inf_param = len(asymp_inf_param_dep)
        n_zero_param = len(asymp_zero_param_dep)
        n_unknown = len(asymp_unknown)
        if n_inf_param > 0 or n_zero_param > 0:
            print("Functions with parameter-dependent asymptotes:", flush=True)
            print(f"  x->inf: {n_inf_param}", flush=True)
            print(f"  x->0+:  {n_zero_param}", flush=True)
        if n_unknown > 0:
            print(f"Functions with unknown asymptotes (post-fit check): "
                  f"{n_unknown}", flush=True)

    # Broadcast to all ranks
    skip_func_idx = comm.bcast(skip_func_idx, root=0)
    asymp_inf_param_dep = comm.bcast(asymp_inf_param_dep, root=0)
    asymp_zero_param_dep = comm.bcast(asymp_zero_param_dep, root=0)
    asymp_unknown = comm.bcast(asymp_unknown, root=0)

    # Handle resume vs fresh start
    completed_func_idx = set()
    if rank == 0:
        if args.resume:
            # First, merge any existing temp files into output
            if temp_dir.exists():
                rank_files = list(temp_dir.glob("results_rank*.hdf5"))
                if len(rank_files) > 0:
                    print(f"Resume: merging {len(rank_files)} temp files "
                          f"into output...", flush=True)
                    ResultsFile.merge(temp_dir, output_path,
                                      delete_rank_files=True,
                                      append_to_existing=True)
                    print("Resume: temp files merged and deleted", flush=True)

            # Now read processed func_idx from the merged output
            if output_path.exists():
                with h5py.File(output_path, 'r') as f:
                    if 'processed_func_idx' in f:
                        completed_func_idx = set(
                            f['processed_func_idx'][:].tolist())
                    elif 'func_idx' in f:
                        # Fallback for old files without processed_func_idx
                        completed_func_idx = set(f['func_idx'][:].tolist())
                if len(completed_func_idx) > 0:
                    n_done = len(completed_func_idx)
                    print(f"Resume: {n_done} functions already processed",
                          flush=True)

            temp_dir.mkdir(parents=True, exist_ok=True)
        else:
            # Fresh start: clear any existing temp files and output
            if temp_dir.exists():
                print("Clearing existing temp directory", flush=True)
                clear_temp_dir(temp_dir)
            if output_path.exists():
                print(f"Deleting existing output file: {output_path}",
                      flush=True)
                output_path.unlink()
            temp_dir.mkdir(parents=True, exist_ok=True)

    # Broadcast completed_func_idx to all ranks
    completed_func_idx = comm.bcast(completed_func_idx, root=0)
    comm.Barrier()

    # Build job queue (filter out completed and skipped functions)
    all_idx = range(len(equations))
    job_queue = [i for i in all_idx
                 if i not in completed_func_idx and i not in skip_func_idx]

    # Load and bin halos on rank 0, then broadcast to all
    if rank == 0:
        if halos_path.suffix in ['.hdf5', '.h5']:
            halos = cdmprof.data.load_from_hdf5(halos_path)
        else:
            halos = cdmprof.load_from_folder(halos_path)
        n_sample = fit_config.get('n_sample', 0)
        binned = halos.bin(
            nbin=fit_config['nbin'],
            n_sample=n_sample if n_sample > 0 else None,
            seed=42)
        n_halos = halos.n_halos
        del halos

        print(f"Run: {runname}, complexity: {args.complexity}", flush=True)
        print(f"Halos: {halos_path}", flush=True)
        n_skipped = len(skip_func_idx)
        n_completed = len(completed_func_idx)
        print(f"Functions: {len(job_queue)} to fit "
              f"({n_skipped} skipped, {n_completed} completed, "
              f"{len(equations)} total)", flush=True)
        print(f"Halos: {n_halos}", flush=True)
        if n_sample > 0:
            print(f"Downsampling: {n_sample} particles per halo", flush=True)
        print(f"Total fits: {len(job_queue) * n_halos}", flush=True)
        print(f"Output: {output_path}", flush=True)
        print(f"Temp dir: {temp_dir}", flush=True)
        print("", flush=True)
    else:
        binned = None
        n_halos = None

    # Broadcast binned data to all ranks
    binned = comm.bcast(binned, root=0)
    n_halos = comm.bcast(n_halos, root=0)

    if size == 1:
        # Single process mode: do everything on one CPU
        print("Running in single-process mode", flush=True)
        optimizer = fit_config.get('optimizer', 'neldermead')
        print(f"Optimizer: {optimizer}", flush=True)
        asymp_n_halos = fit_config.get('asymp_n_halos', 10)
        if asymp_n_halos > 0:
            print(f"Asymptote checks: {asymp_n_halos} random halos",
                  flush=True)
        else:
            print("Asymptote checks: all halos", flush=True)

        # Compute NFW per-halo scores upfront for early stopping comparison
        nfw_score = None
        nfw_per_halo = None

        # Check if NFW early stopping might be enabled
        nfw_early_stop_requested = (
            fit_config.get('nfw_early_stop_enabled', False)
            and len(fit_config.get('nfw_early_stop_halos', [])) > 0)

        if nfw_early_stop_requested:
            print("Computing NFW reference scores for early stopping...",
                  flush=True)
            with warnings.catch_warnings():
                warnings.filterwarnings("ignore", message="reimporting")
                nfw_score, nfw_bic, nfw_per_halo = compute_nfw_scores(
                    binned, fit_config, return_per_halo=True)
            if nfw_per_halo is None or not np.any(~np.isnan(nfw_per_halo)):
                print("NFW fitting failed, disabling NFW early stopping",
                      flush=True)
                nfw_per_halo = None

        # Setup NFW early stop config (handles None nfw_per_halo)
        nfw_config = setup_nfw_early_stop(fit_config, nfw_per_halo)

        if nfw_config['enabled']:
            print(f"NFW avg score: {nfw_config['avg_all']:.4f}", flush=True)
            for j, (halos, factor) in enumerate(nfw_config['tiers'], 1):
                thresh = nfw_config['avg_all'] + factor
                print(f"NFW early stop tier {j}: n>={halos}, "
                      f"avg>{thresh:.4f}", flush=True)

        # Buffer for results - write every N functions
        results_buffer = []
        write_buffer_size = fit_config.get('write_buffer_size', 10)
        temp_output = temp_dir / "results_rank0.hdf5"

        negative_loss_func_idx = set()
        processed_func_idx = set()  # Track all attempted functions

        n_funcs = len(job_queue)
        t_start = time()
        total_fit_time = 0.0

        early_stop_threshold = fit_config.get('early_stop_failures', 5)

        for i, func_idx in enumerate(job_queue):
            # Write results every N functions for resume support
            # Check at start so continue statements don't skip the write
            if i > 0 and i % write_buffer_size == 0:
                has_data = (len(results_buffer) > 0
                            or len(negative_loss_func_idx) > 0
                            or len(processed_func_idx) > 0)
                if has_data:
                    ResultsFile(temp_output).append(
                        results_buffer, equations, negative_loss_func_idx,
                        processed_func_idx, nfw_score)
                    results_buffer = []  # Clear buffer after writing

            t_func_start = time()
            expr_str = equations[func_idx]

            # Mark as processed regardless of outcome
            processed_func_idx.add(func_idx)

            # Print progress
            print(f"[{i+1}/{n_funcs}] Fitting '{expr_str}'", flush=True)

            # Skip bad functions silently
            if cdmprof.fitting.is_bad_function(expr_str):
                continue

            try:
                fitter = cdmprof.compile_fitter(expr_str)
            except Exception as e:
                print(f"Failed to compile func {func_idx} '{expr_str}': {e}",
                      flush=True)
                continue

            # Fit to all halos
            t_fit_start = time()
            fit_result = fit_function_to_halos(
                func_idx, fitter, binned, fit_config,
                nfw_config, nfw_per_halo, log_prefix="")
            func_fit_time = time() - t_fit_start
            total_fit_time += func_fit_time

            # Handle early stopping
            if fit_result['early_stopped']:
                print(f"Func {func_idx} early stopped after "
                      f"{early_stop_threshold} failures", flush=True)
                continue

            if fit_result['nfw_early_stopped']:
                n_fitted = len(fit_result['results'])
                func_avg = np.mean([r[2] / np.sum(binned['bin_counts'][r[1]])
                                    for r in fit_result['results']])
                print(f"NFW early stopped '{expr_str}' "
                      f"(n={n_fitted}, avg={func_avg:.4f}, "
                      f"nfw={fit_result['nfw_avg']:.4f})", flush=True)
                continue

            # Check if function should be rejected
            n_success = len(fit_result['results'])

            if n_success == 0:
                if fit_result['n_negative_loss'] > 0:
                    negative_loss_func_idx.add(func_idx)
                    print(f"Func {func_idx} rejected (negative loss) "
                          f"'{expr_str}'", flush=True)
                else:
                    print(f"All fits failed for func {func_idx} '{expr_str}'",
                          flush=True)
            else:
                results_buffer.extend(fit_result['results'])

            func_time = time() - t_func_start
            elapsed = time() - t_start
            funcs_done = i + 1
            avg_per_func = elapsed / funcs_done
            remaining = avg_per_func * (n_funcs - funcs_done)

            if remaining >= 3600:
                eta_str = f"{remaining / 3600:.1f} h"
            elif remaining >= 60:
                eta_str = f"{remaining / 60:.1f} min"
            else:
                eta_str = f"{remaining:.1f} s"

            print(f"Completed {funcs_done}/{n_funcs} | "
                  f"this: {func_time:.1f}s (fit={func_fit_time:.1f}s) | "
                  f"avg: {avg_per_func:.1f}s/func | ETA: {eta_str}",
                  flush=True)

        # Flush any remaining buffered results
        has_data = (len(results_buffer) > 0 or len(negative_loss_func_idx) > 0
                    or len(processed_func_idx) > 0)
        if has_data:
            ResultsFile(temp_output).append(
                results_buffer, equations, negative_loss_func_idx,
                processed_func_idx, nfw_score)

        # Compute npart per halo (needed for merge and ranking)
        npart_per_halo = [np.sum(bc) for bc in binned['bin_counts']]

        # Merge all results (append to existing if resuming)
        # Pass npart_per_halo to filter params for functions worse than NFW
        t0 = time()
        ResultsFile.merge(temp_dir, output_path, delete_rank_files=True,
                          append_to_existing=args.resume,
                          npart_per_halo=npart_per_halo)
        print(f"[timing] ResultsFile.merge: {time()-t0:.2f}s", flush=True)
        if temp_dir.exists():
            temp_dir.rmdir()
        print(f"All done! Results saved to: {output_path}", flush=True)

        # Print timing summary
        total_time = time() - t_start
        other_time = total_time - total_fit_time
        print("\nTiming breakdown:", flush=True)
        print(f"  Fitting: {total_fit_time:8.1f}s "
              f"({100*total_fit_time/total_time:5.1f}%)", flush=True)
        print(f"  Other:   {other_time:8.1f}s "
              f"({100*other_time/total_time:5.1f}%)", flush=True)
        print(f"  Total:   {total_time:8.1f}s", flush=True)

        # Print failed functions (returns categories for reuse)
        t0 = time()
        failed_categories = print_failed_functions(output_path, equations,
                                                   skip_dict=skip_dict)
        print(f"[timing] print_failed_functions: {time()-t0:.2f}s", flush=True)

        # Compute NFW reference score (reuse if already computed)
        if nfw_score is None:
            t0 = time()
            print("Computing NFW reference score...", flush=True)
            with warnings.catch_warnings():
                warnings.filterwarnings("ignore", message="reimporting")
                nfw_score, nfw_bic = compute_nfw_scores(binned, fit_config)
            print(f"[timing] compute_nfw_scores: {time()-t0:.2f}s", flush=True)

        t0 = time()
        min_success_frac = fit_config.get('min_halo_success_fraction', 0.0)
        failure_percentile = fit_config.get('failure_loss_percentile', 0)
        print_best_results(output_path, equations, npart_per_halo,
                           nfw_score=nfw_score, nfw_bic=nfw_bic,
                           min_success_fraction=min_success_frac,
                           failure_loss_percentile=failure_percentile)
        print(f"[timing] print_best_results: {time()-t0:.2f}s", flush=True)

        # Save results to text files if enabled
        if fit_config.get('save_text_results', True):
            t0 = time()
            write_ranking_to_file(output_path, equations, npart_per_halo,
                                  nfw_score=nfw_score, nfw_bic=nfw_bic,
                                  min_success_fraction=min_success_frac,
                                  failure_loss_percentile=failure_percentile)
            print(f"[timing] write_ranking_to_file: {time()-t0:.2f}s",
                  flush=True)
            t0 = time()
            write_failed_to_files(output_path, failed_categories)
            print(f"[timing] write_failed_to_files: {time()-t0:.2f}s",
                  flush=True)

    else:
        # Multi-process mode: master-worker pattern
        if rank == 0:
            optimizer = fit_config.get('optimizer', 'neldermead')
            print(f"Optimizer: {optimizer}", flush=True)

        # Compute NFW per-halo scores on rank 0 for early stopping comparison
        nfw_score = None
        nfw_per_halo = None

        # Check if NFW early stopping might be enabled
        nfw_early_stop_requested = (
            fit_config.get('nfw_early_stop_enabled', False)
            and len(fit_config.get('nfw_early_stop_halos', [])) > 0)

        if rank == 0 and nfw_early_stop_requested:
            print("Computing NFW reference scores for early stopping...",
                  flush=True)
            with warnings.catch_warnings():
                warnings.filterwarnings("ignore", message="reimporting")
                nfw_score, nfw_bic, nfw_per_halo = compute_nfw_scores(
                    binned, fit_config, return_per_halo=True)
            if nfw_per_halo is None or not np.any(~np.isnan(nfw_per_halo)):
                print("NFW fitting failed, disabling NFW early stopping",
                      flush=True)
                nfw_per_halo = None
            else:
                # Use setup function to get config for printing
                nfw_config = setup_nfw_early_stop(fit_config, nfw_per_halo)
                print(f"NFW avg score: {nfw_config['avg_all']:.4f}",
                      flush=True)
                for j, (halos, factor) in enumerate(nfw_config['tiers'], 1):
                    thresh = nfw_config['avg_all'] + factor
                    print(f"NFW early stop tier {j}: n>={halos}, "
                          f"avg>{thresh:.4f}", flush=True)

        # Broadcast NFW scores to all workers
        nfw_score = comm.bcast(nfw_score, root=0)
        nfw_per_halo = comm.bcast(nfw_per_halo, root=0)

        if rank == 0:
            t_mpi_start = time()
            master_loop(comm, job_queue, fit_config['batch_size'])
            worker_timing = None
        else:
            worker_timing = worker_loop(
                comm, equations, binned, temp_dir, fit_config,
                nfw_per_halo, nfw_score)

        comm.Barrier()

        # Gather timing from all workers to rank 0
        all_timing = comm.gather(worker_timing, root=0)

        if rank == 0:
            # Compute npart per halo (needed for merge and ranking)
            npart_per_halo = [np.sum(bc) for bc in binned['bin_counts']]

            t0 = time()
            ResultsFile.merge(temp_dir, output_path, delete_rank_files=True,
                              append_to_existing=args.resume,
                              npart_per_halo=npart_per_halo)
            print(f"[timing] ResultsFile.merge: {time()-t0:.2f}s", flush=True)
            if temp_dir.exists():
                temp_dir.rmdir()
            print(f"All done! Results saved to: {output_path}", flush=True)

            # Print failed functions (returns categories for reuse)
            t0 = time()
            failed_categories = print_failed_functions(output_path, equations,
                                                       skip_dict=skip_dict)
            print(f"[timing] print_failed_functions: {time()-t0:.2f}s",
                  flush=True)

            # Compute NFW reference score (reuse if already computed)
            if nfw_score is None:
                t0 = time()
                print("Computing NFW reference score...", flush=True)
                with warnings.catch_warnings():
                    warnings.filterwarnings("ignore", message="reimporting")
                    nfw_score, nfw_bic = compute_nfw_scores(binned, fit_config)
                print(f"[timing] compute_nfw_scores: {time()-t0:.2f}s",
                      flush=True)

            t0 = time()
            min_success_frac = fit_config.get('min_halo_success_fraction', 0.0)
            failure_percentile = fit_config.get('failure_loss_percentile', 0)
            print_best_results(output_path, equations, npart_per_halo,
                               nfw_score=nfw_score,
                               min_success_fraction=min_success_frac,
                               failure_loss_percentile=failure_percentile)
            print(f"[timing] print_best_results: {time()-t0:.2f}s", flush=True)

            # Save results to text files if enabled
            if fit_config.get('save_text_results', True):
                t0 = time()
                write_ranking_to_file(
                    output_path, equations, npart_per_halo,
                    nfw_score=nfw_score, min_success_fraction=min_success_frac,
                    failure_loss_percentile=failure_percentile)
                print(f"[timing] write_ranking_to_file: {time()-t0:.2f}s",
                      flush=True)
                t0 = time()
                write_failed_to_files(output_path, failed_categories)
                print(f"[timing] write_failed_to_files: {time()-t0:.2f}s",
                      flush=True)

            # Print worker timing summary
            total_mpi_time = time() - t_mpi_start
            # all_timing[0] is None (master), rest are workers
            worker_timings = [(i, t) for i, t in enumerate(all_timing)
                              if t is not None]
            if len(worker_timings) > 0:
                print(f"\nWorker timing summary "
                      f"({len(worker_timings)} workers):", flush=True)
                print(f"  {'Rank':<6} {'Fitting':>10} {'Other':>10} "
                      f"{'Total':>10}", flush=True)
                print(f"  {'-'*6} {'-'*10} {'-'*10} {'-'*10}", flush=True)
                for rank_i, (fit_t, total_t) in worker_timings:
                    other_t = total_t - fit_t
                    print(f"  {rank_i:<6} {format_time(fit_t):>10} "
                          f"{format_time(other_t):>10} "
                          f"{format_time(total_t):>10}", flush=True)
                # Print totals
                total_fit = sum(t[0] for _, t in worker_timings)
                total_cpu = sum(t[1] for _, t in worker_timings)
                total_other = total_cpu - total_fit
                print(f"  {'-'*6} {'-'*10} {'-'*10} {'-'*10}", flush=True)
                print(f"  {'Total':<6} {format_time(total_fit):>10} "
                      f"{format_time(total_other):>10} "
                      f"{format_time(total_cpu):>10}", flush=True)
                print(f"  Wall time: {format_time(total_mpi_time)}",
                      flush=True)

    # Clean up per-job CFFI cache directory
    if rank == 0 and cffi_cache.exists():
        shutil.rmtree(cffi_cache)
